// ======================================================
// SERVER HERO PREMIUM V5.0
// app.js - FULL COMPLETE VERSION (13 MISSIONS)
// ======================================================
"use strict";
if (typeof missions === "undefined" || !Array.isArray(missions)) throw new Error("missions.js tidak dimuatkan atau data missions tidak sah.");
const TOTAL_MISSIONS = missions.length;
const STORAGE_KEYS = Object.freeze({player:"serverHeroPlayerV4",achievements:"serverHeroAchievementsV4",history:"serverHeroHistoryV4",exportSave:"serverHeroExportV5",dailyClaim:"serverHeroDailyClaimV5",masterUnlocked:"serverHeroMasterUnlockedV4"});
const DEFAULT_PLAYER = Object.freeze({name:"AGENT",xp:500,level:1,completed:0,streak:1,rank:"Beginner"});
const ACHIEVEMENTS = Object.freeze([
{id:"first-mission",title:"Misi Pertama",target:1,rewardXP:100},
{id:"server-explorer",title:"Server Explorer",target:3,rewardXP:250},
{id:"server-specialist",title:"Server Specialist",target:5,rewardXP:400},
{id:"server-hero",title:"Server Hero",target:8,rewardXP:800},
{id:"server-master",title:"Server Hero Master",target:13,rewardXP:1500}
]);
let player=loadObject(STORAGE_KEYS.player,DEFAULT_PLAYER);
let unlockedAchievements=loadArray(STORAGE_KEYS.achievements);
let missionHistory=loadArray(STORAGE_KEYS.history);
const elements=Object.freeze({missions:document.getElementById("missions"),xp:document.getElementById("xp"),level:document.getElementById("level"),rank:document.getElementById("rank"),rankText:document.getElementById("rankText"),streak:document.getElementById("streak"),achievementCount:document.getElementById("achievementCount"),completion:document.getElementById("completion"),progress:document.getElementById("progress"),percent:document.getElementById("percent"),dailyMission:document.getElementById("dailyMission"),masterPanel:document.getElementById("masterPanel")});
function loadObject(key,fallback){try{const raw=localStorage.getItem(key);if(!raw)return{...fallback};const parsed=JSON.parse(raw);if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))return{...fallback};return{...fallback,...parsed};}catch(error){console.error(`Gagal membaca data ${key}:`,error);return{...fallback};}}
function loadArray(key){try{const raw=localStorage.getItem(key);if(!raw)return[];const parsed=JSON.parse(raw);return Array.isArray(parsed)?parsed:[];}catch(error){console.error(`Gagal membaca data ${key}:`,error);return[];}}
function saveJSON(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch(error){console.error(`Gagal menyimpan data ${key}:`,error);return false;}}
function saveGameData(){saveJSON(STORAGE_KEYS.player,player);saveJSON(STORAGE_KEYS.achievements,unlockedAchievements);saveJSON(STORAGE_KEYS.history,missionHistory);}
function setText(element,value){if(element)element.textContent=String(value);}
function escapeHTML(value){const div=document.createElement("div");div.textContent=String(value??"");return div.innerHTML;}
function getMissionById(id){return missions.find(m=>m.id===Number(id))||null;}
function missionCompleteKey(id){return `lesson${id}Complete`;}
function missionRewardKey(id){return `lesson${id}RewardedV4`;}
function isMissionCompleted(id){return localStorage.getItem(missionCompleteKey(id))==="true";}
function isMissionRewarded(id){return localStorage.getItem(missionRewardKey(id))==="true";}
function isMissionUnlocked(id){return Number(id)===1||isMissionCompleted(Number(id)-1);}
function getCompletedMissionCount(){return missions.filter(m=>isMissionCompleted(m.id)).length;}
function getTodayKey(){const t=new Date();return `${t.getFullYear()}-${String(t.getMonth()+1).padStart(2,"0")}-${String(t.getDate()).padStart(2,"0")}`;}
function calculateLevel(){player.level=Math.max(1,Math.floor(player.xp/500));}
function calculateRank(){if(player.completed>=13)player.rank="SERVER HERO MASTER";else if(player.xp>=12000)player.rank="Legend";else if(player.xp>=9000)player.rank="Master";else if(player.xp>=6500)player.rank="Elite";else if(player.xp>=4000)player.rank="Professional";else if(player.xp>=2000)player.rank="Advanced";else player.rank="Beginner";}
function refreshPlayerCalculations(){player.completed=getCompletedMissionCount();calculateLevel();calculateRank();}
function synchronizeMissionRewards(){let changed=false;missions.forEach(m=>{if(!isMissionCompleted(m.id)||isMissionRewarded(m.id))return;player.xp+=Number(m.xp)||0;localStorage.setItem(missionRewardKey(m.id),"true");addMissionHistory(m);changed=true;});if(changed){player.streak+=1;saveGameData();}}
function updateDashboard(){refreshPlayerCalculations();setText(elements.xp,player.xp);setText(elements.level,player.level);setText(elements.rank,player.rank);setText(elements.rankText,player.rank);setText(elements.streak,`${player.streak} Hari`);setText(elements.achievementCount,unlockedAchievements.length);setText(elements.completion,`${player.completed} / ${TOTAL_MISSIONS}`);const pct=TOTAL_MISSIONS?Math.round((player.completed/TOTAL_MISSIONS)*100):0;if(elements.progress)elements.progress.value=pct;setText(elements.percent,`${pct}%`);updateDailyMission();updateMasterPanel();saveGameData();}
function updateMasterPanel(){if(!elements.masterPanel)return;const done=player.completed>=TOTAL_MISSIONS;elements.masterPanel.classList.toggle("hidden",!done);if(done)localStorage.setItem(STORAGE_KEYS.masterUnlocked,"true");}
function createMissionCards(){if(!elements.missions){console.error('Elemen id="missions" tidak dijumpai.');return;}elements.missions.innerHTML="";missions.forEach(m=>{const completed=isMissionCompleted(m.id),unlocked=isMissionUnlocked(m.id);const card=document.createElement("article");card.className="mission-card";card.dataset.missionId=String(m.id);if(completed)card.classList.add("completed");else if(!unlocked)card.classList.add("locked");const label=completed?"Selesai":unlocked?"Mulakan Misi":"Terkunci";const status=completed?"✅":unlocked?"🔓":"🔒";card.innerHTML=`<div class="mission-header"><div><h2>${escapeHTML(m.icon)} ${escapeHTML(m.title)}</h2><h4>${escapeHTML(m.subtitle)}</h4></div><span class="badge">${Number(m.xp)||0} XP</span></div><p>${escapeHTML(m.description)}</p><div class="mission-info"><span>🎯 ${escapeHTML(m.difficulty)}</span><span>⏱ ${escapeHTML(m.duration)}</span></div><div class="mission-footer"><span class="mission-status">${status}</span><button type="button" ${completed||!unlocked?"disabled":""}>${label}</button></div>`;const button=card.querySelector("button");if(button&&unlocked&&!completed)button.addEventListener("click",()=>openMission(m.id));elements.missions.appendChild(card);});}
function openMission(id){const m=getMissionById(id);if(!m)return showToast("Misi tidak dijumpai.","error");if(!isMissionUnlocked(id))return showToast("Selesaikan misi sebelumnya dahulu.","error");if(!m.page)return showToast("Fail lesson belum ditetapkan.","error");window.location.href=m.page;}
function completeMissionById(id){const m=getMissionById(id);if(!m){showToast("Misi tidak dijumpai.","error");return false;}if(isMissionCompleted(id)){showToast("Misi ini telah selesai.","info");return false;}localStorage.setItem(missionCompleteKey(id),"true");synchronizeMissionRewards();checkAchievements();updateDashboard();createMissionCards();showRewardPopup(m);return true;}
function checkAchievements(){refreshPlayerCalculations();let changed=false;ACHIEVEMENTS.forEach(a=>{if(player.completed>=a.target&&!unlockedAchievements.includes(a.id)){unlockedAchievements.push(a.id);player.xp+=a.rewardXP;changed=true;showToast(`🏆 ${a.title} dibuka! +${a.rewardXP} XP`,"success");}});if(changed){calculateLevel();calculateRank();saveGameData();}updateAchievementCards();}
function updateAchievementCards(){document.querySelectorAll(".achievement-card").forEach(card=>{const id=card.dataset.achievementId;if(id)card.classList.toggle("unlocked",unlockedAchievements.includes(id));});}
function updateDailyMission(){if(!elements.dailyMission)return;const messages=["Lengkapkan satu misi server hari ini.","Jawab satu kuiz misi dengan betul.","Kumpulkan sekurang-kurangnya 250 XP hari ini.","Ulang kaji satu misi yang telah selesai.","Buka satu pelajaran Windows Server baharu."];elements.dailyMission.textContent=messages[new Date().getDate()%messages.length];}
function claimDailyLoginBonus(){const today=getTodayKey();if(localStorage.getItem(STORAGE_KEYS.dailyClaim)===today)return;player.xp+=50;localStorage.setItem(STORAGE_KEYS.dailyClaim,today);saveGameData();setTimeout(()=>{showToast("🎁 Bonus Harian: +50 XP","success");updateDashboard();},500);}
function addMissionHistory(m){missionHistory.unshift({id:m.id,title:m.subtitle,completedAt:new Date().toISOString()});missionHistory=missionHistory.slice(0,50);saveGameData();}
function exportSave(){const payload={version:"5.0",exportedAt:new Date().toISOString(),player,achievements:unlockedAchievements,history:missionHistory,missionStatus:missions.map(m=>({id:m.id,completed:isMissionCompleted(m.id),rewarded:isMissionRewarded(m.id)}))};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`server-hero-save-${getTodayKey()}.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);showToast("Simpanan berjaya dieksport.","success");}
function importSave(){const input=document.createElement("input");input.type="file";input.accept="application/json,.json";input.addEventListener("change",async()=>{const file=input.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());player={...DEFAULT_PLAYER,...(data.player||{})};unlockedAchievements=Array.isArray(data.achievements)?data.achievements:[];missionHistory=Array.isArray(data.history)?data.history:[];if(Array.isArray(data.missionStatus))data.missionStatus.forEach(item=>{const id=Number(item.id);if(!Number.isInteger(id)||id<1||id>TOTAL_MISSIONS)return;localStorage.setItem(missionCompleteKey(id),item.completed?"true":"false");localStorage.setItem(missionRewardKey(id),item.rewarded?"true":"false");});saveGameData();showToast("Simpanan berjaya diimport.","success");setTimeout(()=>window.location.reload(),700);}catch(e){console.error(e);showToast("Fail simpanan tidak sah.","error");}});input.click();}
function resetProgress(){if(!window.confirm("Semua kemajuan misi, XP dan pencapaian akan dipadam. Teruskan?"))return;missions.forEach(m=>{localStorage.removeItem(missionCompleteKey(m.id));localStorage.removeItem(missionRewardKey(m.id));["SimulationCompletedV4","MatchingCompletedV4","SequenceCompletedV4","QuizAnswersV4","QuizScoreV4","QuizPassedV4","CurrentQuestionV4"].forEach(s=>localStorage.removeItem(`lesson${m.id}${s}`));});Object.values(STORAGE_KEYS).forEach(k=>localStorage.removeItem(k));player={...DEFAULT_PLAYER};unlockedAchievements=[];missionHistory=[];saveGameData();window.alert("Kemajuan telah direset.");window.location.reload();}
function showToast(message,type="info"){const old=document.querySelector(".toast");if(old)old.remove();const toast=document.createElement("div");toast.className=`toast ${type}`;toast.textContent=message;document.body.appendChild(toast);requestAnimationFrame(()=>toast.classList.add("show"));setTimeout(()=>toast.classList.remove("show"),2800);setTimeout(()=>toast.remove(),3400);}
function showRewardPopup(m){const old=document.querySelector(".reward-popup");if(old)old.remove();const popup=document.createElement("div");popup.className="reward-popup";popup.innerHTML=`<h2>🎉 Misi Selesai</h2><p>${escapeHTML(m.subtitle)}</p><p class="reward-xp">+${Number(m.xp)||0} XP</p><button type="button">Teruskan</button>`;document.body.appendChild(popup);popup.querySelector("button")?.addEventListener("click",()=>popup.remove());requestAnimationFrame(()=>popup.classList.add("show"));}
window.openMission=openMission;window.exportSave=exportSave;window.importSave=importSave;window.resetProgress=resetProgress;window.serverHeroCompleteMission=completeMissionById;
window.SERVER_HERO={version:"5.0",getPlayer:()=>({...player}),getAchievements:()=>[...unlockedAchievements],getHistory:()=>[...missionHistory],completeMission:completeMissionById,refresh(){synchronizeMissionRewards();checkAchievements();updateDashboard();createMissionCards();}};
function initializeServerHero(){synchronizeMissionRewards();checkAchievements();claimDailyLoginBonus();updateDashboard();createMissionCards();console.log("SERVER HERO PREMIUM V5.0 READY",{totalMissions:TOTAL_MISSIONS,completed:player.completed,xp:player.xp});}
initializeServerHero();
