const app=document.getElementById("kpApp");let state=SHStorage.load();const lang=state.lang||"ms";let step=0,sequenceClicks=[],answers={};
const slides=[
{icon:"💿",title:{ms:"Misi KP05: Pemasangan Windows Server 2019",en:"KP05 Mission: Windows Server 2019 Installation"},lead:{ms:"Pelajari proses pemasangan Windows Server 2019 daripada boot media sehingga konfigurasi awal Administrator.",en:"Learn the Windows Server 2019 installation process from boot media to initial Administrator configuration."},body:()=>`<div class="story-alert"><strong>🚨 Mission Briefing</strong>${lang==="ms"?"Sebuah server baharu tiba tanpa sistem operasi. Pasang Windows Server 2019 dengan konfigurasi yang betul sebelum digunakan dalam rangkaian organisasi.":"A new server has arrived without an operating system. Install Windows Server 2019 correctly before it is used on the organisation's network."}</div><div class="card-grid three">${card("💿",lang==="ms"?"Media Pemasangan":"Installation Media",lang==="ms"?"Sediakan ISO, DVD atau USB bootable.":"Prepare an ISO, DVD or bootable USB.")}${card("⚙️",lang==="ms"?"Edisi & Partisi":"Edition & Partition",lang==="ms"?"Pilih edisi dan cakera dengan betul.":"Select the correct edition and disk.")}${card("👤",lang==="ms"?"Administrator":"Administrator",lang==="ms"?"Lengkapkan konfigurasi awal dan kata laluan.":"Complete initial setup and password configuration.")}</div>`},
{icon:"📋",title:{ms:"Persediaan Sebelum Pemasangan",en:"Pre-installation Preparation"},lead:{ms:"Semak perkakasan, media pemasangan dan backup.",en:"Check hardware, installation media and backups."},body:()=>`<div class="card-grid two">${card("🧠",lang==="ms"?"Keperluan Perkakasan":"Hardware Requirements",lang==="ms"?"Pastikan CPU 64-bit, RAM dan storan mencukupi.":"Ensure the 64-bit CPU, RAM and storage are sufficient.")}${card("💾",lang==="ms"?"Media Pemasangan":"Installation Media",lang==="ms"?"Gunakan media yang sah dan tidak rosak.":"Use valid, undamaged media.")}${card("🛡️","Backup",lang==="ms"?"Backup data penting sebelum pemasangan.":"Back up important data before installation.")}${card("🔑","Product Key",lang==="ms"?"Sediakan jika lesen memerlukannya.":"Prepare it if required by the licence.")}</div>`},
{icon:"🔁",title:{ms:"Tetapan Boot",en:"Boot Configuration"},lead:{ms:"Boot server daripada media pemasangan.",en:"Boot the server from installation media."},body:()=>`<div class="install-flow">${flow(1,"BIOS/UEFI",lang==="ms"?"Masuk menggunakan kekunci pengilang.":"Enter using the manufacturer's key.")}${flow(2,lang==="ms"?"Boot Order":"Boot Order",lang==="ms"?"Letakkan USB/DVD sebagai boot pertama.":"Set USB/DVD as the first boot device.")}${flow(3,lang==="ms"?"Simpan & Restart":"Save & Restart",lang==="ms"?"Simpan perubahan dan mula semula.":"Save changes and restart.")}</div>`},
{icon:"🪟",title:{ms:"Pilih Edisi Windows Server",en:"Select Windows Server Edition"},lead:{ms:"Pilih edisi mengikut lesen dan keperluan organisasi.",en:"Choose the edition according to licence and organisational needs."},body:()=>`<div class="choice-grid">${choice("Windows Server 2019 Standard",lang==="ms"?"Sesuai untuk virtualisasi ringan.":"Suitable for light virtualisation.")}${choice("Windows Server 2019 Datacenter",lang==="ms"?"Sesuai untuk pusat data dan virtualisasi besar.":"Suitable for data centres and large-scale virtualisation.")}${choice("Server Core",lang==="ms"?"Antaramuka minimum dan lebih ringan.":"Minimal interface and lighter footprint.")}${choice("Desktop Experience",lang==="ms"?"GUI penuh untuk latihan asas.":"Full GUI for introductory training.")}</div>`},
{icon:"🧩",title:{ms:"Jenis Pemasangan",en:"Installation Type"},lead:{ms:"Untuk pemasangan bersih, pilih Custom Installation.",en:"For a clean installation, choose Custom Installation."},body:()=>`<div class="choice-grid">${choice(lang==="ms"?"Upgrade":"Upgrade",lang==="ms"?"Mengekalkan fail dan tetapan apabila disokong.":"Keeps files and settings when supported.")}${choice("Custom: Install Windows Only",lang==="ms"?"Untuk pemasangan baharu dan partisi.":"For a fresh installation and partitioning.")}</div><div class="warning-box"><strong>${lang==="ms"?"Peringatan":"Reminder"}:</strong> ${lang==="ms"?"Custom Installation boleh memadam data pada partisi dipilih.":"Custom Installation may erase data on the selected partition."}</div>`},
{icon:"💽",title:{ms:"Partisi Cakera",en:"Disk Partitioning"},lead:{ms:"Pilih cakera dan partisi dengan teliti.",en:"Select the disk and partition carefully."},body:()=>`<div class="disk-bar"><div class="disk-system"><b>System</b></div><div class="disk-os"><b>Windows Server C:</b></div><div class="disk-data"><b>Data D:</b></div></div><div class="card-grid two">${card("➕","New",lang==="ms"?"Cipta partisi baharu.":"Create a new partition.")}${card("🗑️","Delete",lang==="ms"?"Padam partisi dan datanya.":"Delete a partition and its data.")}${card("🧼","Format",lang==="ms"?"Format partisi dipilih.":"Format the selected partition.")}${card("📂","Load Driver",lang==="ms"?"Muatkan driver storan.":"Load a storage driver.")}</div>`},
{icon:"⏳",title:{ms:"Proses Pemasangan",en:"Installation Process"},lead:{ms:"Setup menyalin fail, memasang ciri dan restart beberapa kali.",en:"Setup copies files, installs features and restarts several times."},body:()=>`<div class="install-flow">${flow(1,"Copying Windows Files",lang==="ms"?"Fail asas disalin.":"Core files are copied.")}${flow(2,"Installing Features",lang==="ms"?"Ciri sistem dipasang.":"System features are installed.")}${flow(3,"Restart",lang==="ms"?"Server restart secara automatik.":"The server restarts automatically.")}</div>`},
{icon:"👤",title:{ms:"Tetapan Administrator",en:"Administrator Setup"},lead:{ms:"Tetapkan kata laluan Administrator yang kukuh.",en:"Set a strong Administrator password."},body:()=>`<div class="card-grid two">${card("🔐",lang==="ms"?"Kata Laluan Kukuh":"Strong Password",lang==="ms"?"Gunakan huruf besar, kecil, nombor dan simbol.":"Use uppercase, lowercase, numbers and symbols.")}${card("🖥️",lang==="ms"?"Login Pertama":"First Login",lang==="ms"?"Login sebagai Administrator.":"Sign in as Administrator.")}${card("⚙️",lang==="ms"?"Konfigurasi Awal":"Initial Configuration",lang==="ms"?"Tetapkan nama server, masa, rangkaian dan update.":"Configure server name, time, networking and updates.")}${card("🧾",lang==="ms"?"Rekod Selamat":"Secure Record",lang==="ms"?"Simpan maklumat akses ikut polisi.":"Store access information according to policy.")}</div>`},
{icon:"🎮",title:{ms:"Aktiviti Susun Langkah",en:"Sequence Activity"},lead:{ms:"Tekan langkah mengikut urutan pemasangan yang betul.",en:"Tap the steps in the correct installation order."},sequence:true},
{icon:"🧠",title:{ms:"Kuiz KP05",en:"KP05 Quiz"},lead:{ms:"Jawab semua 10 soalan untuk menamatkan KP05.",en:"Answer all 10 questions to complete KP05."},quiz:true}
];
const sequence=[{ms:"Boot daripada media pemasangan",en:"Boot from installation media"},{ms:"Pilih bahasa dan papan kekunci",en:"Choose language and keyboard"},{ms:"Pilih edisi Windows Server",en:"Select Windows Server edition"},{ms:"Pilih Custom Installation",en:"Choose Custom Installation"},{ms:"Pilih atau cipta partisi",en:"Select or create a partition"},{ms:"Tetapkan kata laluan Administrator",en:"Set the Administrator password"}];
const quiz=[
{q:{ms:"Apakah yang perlu disediakan sebelum pemasangan?",en:"What should be prepared before installation?"},o:{ms:["Media pemasangan dan semakan perkakasan","Warna rak","Nama pengguna sahaja"],en:["Installation media and hardware checks","Rack colour","Only a username"]},a:0},
{q:{ms:"Server perlu boot daripada?",en:"The server must boot from?"},o:{ms:["USB/DVD pemasangan","Desktop Windows","Fail teks"],en:["Installation USB/DVD","Windows desktop","A text file"]},a:0},
{q:{ms:"Edisi untuk virtualisasi besar?",en:"Edition for large-scale virtualisation?"},o:{ms:["Datacenter","Standard sahaja","Home"],en:["Datacenter","Standard only","Home"]},a:0},
{q:{ms:"Kelebihan Desktop Experience?",en:"Advantage of Desktop Experience?"},o:{ms:["GUI penuh","Tiada antaramuka","Tidak boleh dikonfigurasi"],en:["Full GUI","No interface","Cannot be configured"]},a:0},
{q:{ms:"Jenis pemasangan bersih?",en:"Clean installation type?"},o:{ms:["Custom","Upgrade","Repair sahaja"],en:["Custom","Upgrade","Repair only"]},a:0},
{q:{ms:"Risiko Delete Partition?",en:"Risk of Delete Partition?"},o:{ms:["Data partisi dipadam","RAM bertambah","Nama server berubah"],en:["Partition data is erased","RAM increases","Server name changes"]},a:0},
{q:{ms:"Fungsi Load Driver?",en:"Function of Load Driver?"},o:{ms:["Memuatkan driver storan","Menukar kata laluan","Memasang antivirus"],en:["Load a storage driver","Change a password","Install antivirus"]},a:0},
{q:{ms:"Apa berlaku semasa setup?",en:"What happens during setup?"},o:{ms:["Fail disalin dan server restart","Semua pengguna dipadam","Tiada perubahan"],en:["Files are copied and the server restarts","All users are deleted","Nothing changes"]},a:0},
{q:{ms:"Kata laluan Administrator perlu?",en:"Administrator password should be?"},o:{ms:["Kukuh dan selamat","1234","Sama dengan nama server"],en:["Strong and secure","1234","The same as the server name"]},a:0},
{q:{ms:"Konfigurasi awal selepas login?",en:"Initial configuration after login?"},o:{ms:["Nama server, masa, rangkaian dan update","Wallpaper sahaja","Padam semua log"],en:["Server name, time, network and updates","Only wallpaper","Delete all logs"]},a:0}
];
function card(i,t,x){return `<article class="info-card"><span>${i}</span><h3>${t}</h3><p>${x}</p></article>`}function flow(n,t,x){return `<article class="install-step"><b>${n}</b><div><h3>${t}</h3><p>${x}</p></div></article>`}function choice(t,x){return `<article class="choice-card"><strong>${t}</strong><p>${x}</p></article>`}
function render(){const s=slides[step];app.innerHTML=`<div class="kp-shell"><header class="kp-header"><button onclick="goDashboard()">← Dashboard</button><div class="kp-progress"><i style="width:${((step+1)/slides.length)*100}%"></i></div><span>${step+1}/${slides.length}</span></header><section class="card kp-stage"><span class="kp-chip">KP05</span><div class="kp-hero-icon">${s.icon}</div><h1>${s.title[lang]}</h1><p class="kp-lead">${s.lead[lang]}</p>${s.sequence?renderSequence():s.quiz?renderQuiz():s.body()}<div id="feedback" class="feedback"></div><div class="kp-nav"><button class="secondary" onclick="previous()" ${step===0?"disabled":""}>← ${lang==="ms"?"Sebelumnya":"Previous"}</button><button onclick="next()">${step===slides.length-1?(lang==="ms"?"SELESAIKAN KP":"COMPLETE KP"):(lang==="ms"?"Seterusnya":"Next")} →</button></div></section></div>`}
function renderSequence(){const a=[...sequence.map((x,i)=>({i,text:x[lang]}))].sort(()=>Math.random()-.5);return `<div class="sequence-list">${a.map(x=>`<button class="sequence-btn" onclick="pickSequence(${x.i},this)">${x.text}</button>`).join("")}</div>`}
function pickSequence(i,b){const e=sequenceClicks.length;if(i===e){sequenceClicks.push(i);b.classList.add("correct");b.disabled=true;feedback(lang==="ms"?"Urutan betul. Teruskan.":"Correct order. Continue.","good")}else{feedback(lang==="ms"?"Belum tepat. Pilih langkah lebih awal.":"Not correct yet. Choose an earlier step.","bad");SHV5?.sound?.("wrong")}}
function renderQuiz(){return `<div class="quiz-list">${quiz.map((q,qi)=>`<article class="quiz-card"><h3>${qi+1}. ${q.q[lang]}</h3>${q.o[lang].map((o,oi)=>`<button class="quiz-option ${answers[qi]===oi?"selected":""}" onclick="answer(${qi},${oi},this)">${String.fromCharCode(65+oi)}. ${o}</button>`).join("")}</article>`).join("")}</div>`}
function answer(q,o,b){answers[q]=o;document.querySelectorAll(`.quiz-card:nth-child(${q+1}) .quiz-option`).forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}function feedback(x,t){const e=document.getElementById("feedback");if(e){e.textContent=x;e.className="feedback "+t}}function previous(){if(step>0){step--;render()}}function next(){if(slides[step].sequence&&sequenceClicks.length<sequence.length){feedback(lang==="ms"?"Lengkapkan semua langkah dahulu.":"Complete all steps first.","bad");return}if(slides[step].quiz){if(Object.keys(answers).length<quiz.length){feedback(lang==="ms"?"Jawab semua soalan dahulu.":"Answer all questions first.","bad");return}complete();return}if(step<slides.length-1){step++;render()}}
function complete(){let correct=0;quiz.forEach((q,i)=>{if(answers[i]===q.a)correct++});const score=Math.round(correct/quiz.length*100);state.completedKP=state.completedKP||[];const first=!state.completedKP.includes(5);if(first)state.completedKP.push(5);state.unlocked=Math.max(state.unlocked||5,6);state.badges=state.badges||[];if(first){state.xp=(state.xp||0)+180+(correct*15);state.coins=(state.coins||0)+100}if(state.completedKP.length>=5&&!state.badges.includes("five-kp"))state.badges.push("five-kp");SHStorage.save(state);SHV5?.sound?.("complete");app.innerHTML=`<section class="center"><div class="card hero"><div class="complete-icon">🎉</div><h1>${lang==="ms"?"Tahniah!":"Congratulations!"}</h1><div class="score-ring" style="--score:${score*3.6}deg"><b>${score}%</b></div><p>${lang==="ms"?"KP05 selesai dan KP06 telah dibuka.":"KP05 is complete and KP06 has been unlocked."}</p><p><strong>${first?`+${180+(correct*15)} XP · +100 Coin`:(lang==="ms"?"Ganjaran telah dituntut.":"Reward already claimed.")}</strong></p><button class="primary" onclick="goDashboard()">Dashboard</button></div></section>`}function goDashboard(){window.location.href="index.html"}render();