const app=document.getElementById("kpApp");
let state=SHStorage.load();
const lang=state.lang||"ms";
let step=0,labStep=0,selectedLeft=null;
const matched=new Set();
let answers={};
let lab={zoneName:"",hostName:"",ip:"",tested:false};

const slides=[
{icon:"🌐",title:{ms:"Misi KP07: Konfigurasi DNS",en:"KP07 Mission: DNS Configuration"},lead:{ms:"Konfigurasikan DNS supaya nama server boleh diterjemahkan kepada alamat IP.",en:"Configure DNS so server names can be translated into IP addresses."},body:()=>`<div class="story-alert"><strong>🚨 Mission Briefing</strong>${lang==="ms"?"Klien tidak dapat mencari domain walaupun Domain Controller aktif. DNS perlu dikonfigurasi dan diuji segera.":"Clients cannot locate the domain even though the Domain Controller is active. DNS must be configured and tested immediately."}</div><div class="card-grid three">${card("🧠",lang==="ms"?"Objektif 1":"Objective 1",lang==="ms"?"Memahami fungsi DNS dan resolusi nama.":"Understand DNS and name resolution.")}${card("🗂️",lang==="ms"?"Objektif 2":"Objective 2",lang==="ms"?"Mencipta Forward Lookup Zone dan rekod Host (A).":"Create a Forward Lookup Zone and Host (A) record.")}${card("🔍",lang==="ms"?"Objektif 3":"Objective 3",lang==="ms"?"Menguji DNS menggunakan nslookup dan ping.":"Test DNS using nslookup and ping.")}</div>`},
{icon:"🔄",title:{ms:"Cara DNS Berfungsi",en:"How DNS Works"},lead:{ms:"DNS menukar nama mudah dibaca kepada alamat IP yang digunakan oleh komputer.",en:"DNS converts human-readable names into IP addresses used by computers."},body:()=>`<div class="dns-flow"><div><span>💻</span><b>Client</b></div><span>→</span><div><span>❓</span><b>DNS Query</b></div><span>→</span><div><span>🌐</span><b>DNS Server</b></div><span>→</span><div><span>📍</span><b>192.168.10.10</b></div></div>`},
{icon:"📚",title:{ms:"Jenis Rekod DNS",en:"DNS Record Types"},lead:{ms:"Setiap rekod mempunyai fungsi khusus dalam zon DNS.",en:"Each record has a specific function in a DNS zone."},body:()=>`<div class="card-grid three">${card("🅰️","A",lang==="ms"?"Nama host kepada alamat IPv4.":"Host name to IPv4 address.")}${card("6️⃣","AAAA",lang==="ms"?"Nama host kepada alamat IPv6.":"Host name to IPv6 address.")}${card("🔗","CNAME",lang==="ms"?"Alias kepada nama kanonik.":"Alias to a canonical name.")}${card("✉️","MX",lang==="ms"?"Menentukan pelayan e-mel.":"Identifies a mail server.")}${card("↩️","PTR",lang==="ms"?"Alamat IP kepada nama host.":"IP address to host name.")}${card("🏷️","NS",lang==="ms"?"Menentukan authoritative name server.":"Identifies the authoritative name server.")}</div>`},
{icon:"🖥️",title:{ms:"Virtual Lab: DNS Manager",en:"Virtual Lab: DNS Manager"},lead:{ms:"Cipta zon serverhero.local, tambah rekod Host (A) dan uji resolusi nama.",en:"Create the serverhero.local zone, add a Host (A) record and test name resolution."},lab:true},
{icon:"🧯",title:{ms:"Penyelesaian Masalah DNS",en:"DNS Troubleshooting"},lead:{ms:"Semak konfigurasi asas sebelum menyimpulkan perkhidmatan DNS gagal.",en:"Check the basic configuration before concluding DNS has failed."},body:()=>`<div class="card-grid two">${card("📍",lang==="ms"?"Preferred DNS Server":"Preferred DNS Server",lang==="ms"?"Pastikan klien menggunakan IP DNS dalaman.":"Ensure the client uses the internal DNS IP.")}${card("🔍","nslookup",lang==="ms"?"Semak server DNS dan jawapan rekod.":"Check the DNS server and record response.")}${card("🧹","ipconfig /flushdns",lang==="ms"?"Kosongkan cache DNS klien.":"Clear the client DNS cache.")}${card("📡","ping",lang==="ms"?"Uji sama ada nama berjaya diterjemah kepada IP.":"Test whether the name resolves to an IP address.")}</div>`},
{icon:"🎮",title:{ms:"Aktiviti Padanan DNS",en:"DNS Matching Activity"},lead:{ms:"Padankan rekod DNS dengan fungsinya.",en:"Match each DNS record with its function."},activity:true},
{icon:"🧠",title:{ms:"Kuiz KP07",en:"KP07 Quiz"},lead:{ms:"Jawab semua 10 soalan untuk menamatkan KP07.",en:"Answer all 10 questions to complete KP07."},quiz:true}
];

const pairs=[
{l:{ms:"A Record",en:"A Record"},r:{ms:"Nama host kepada IPv4",en:"Host name to IPv4"}},
{l:{ms:"CNAME",en:"CNAME"},r:{ms:"Alias kepada nama kanonik",en:"Alias to a canonical name"}},
{l:{ms:"MX",en:"MX"},r:{ms:"Menentukan pelayan e-mel",en:"Identifies a mail server"}},
{l:{ms:"PTR",en:"PTR"},r:{ms:"Alamat IP kepada nama host",en:"IP address to host name"}}
];

const quiz=[
{q:{ms:"Apakah fungsi utama DNS?",en:"What is the main function of DNS?"},o:{ms:["Menterjemah nama kepada IP","Menyimpan fail pengguna","Mengawal suhu"],en:["Translate names to IP addresses","Store user files","Control temperature"]},a:0},
{q:{ms:"Rekod untuk IPv4 ialah?",en:"Which record is used for IPv4?"},o:{ms:["A","MX","PTR"],en:["A","MX","PTR"]},a:0},
{q:{ms:"Rekod alias ialah?",en:"Which record is an alias?"},o:{ms:["CNAME","A","NS"],en:["CNAME","A","NS"]},a:0},
{q:{ms:"Rekod pelayan e-mel ialah?",en:"Which record identifies a mail server?"},o:{ms:["MX","PTR","AAAA"],en:["MX","PTR","AAAA"]},a:0},
{q:{ms:"Forward Lookup menukar?",en:"Forward Lookup converts?"},o:{ms:["Nama kepada IP","IP kepada nama","MAC kepada IP"],en:["Name to IP","IP to name","MAC to IP"]},a:0},
{q:{ms:"Reverse Lookup menggunakan rekod?",en:"Reverse Lookup uses which record?"},o:{ms:["PTR","A","CNAME"],en:["PTR","A","CNAME"]},a:0},
{q:{ms:"Nama zon dalam modul?",en:"What is the zone name in the module?"},o:{ms:["serverhero.local","serverhero","local"],en:["serverhero.local","serverhero","local"]},a:0},
{q:{ms:"Arahan untuk menguji DNS?",en:"Which command tests DNS?"},o:{ms:["nslookup","format","shutdown"],en:["nslookup","format","shutdown"]},a:0},
{q:{ms:"Arahan kosongkan cache DNS?",en:"Which command clears DNS cache?"},o:{ms:["ipconfig /flushdns","ping -t","diskpart"],en:["ipconfig /flushdns","ping -t","diskpart"]},a:0},
{q:{ms:"Klien perlu menggunakan?",en:"The client should use?"},o:{ms:["IP DNS dalaman","Sebarang IP rawak","Alamat broadcast"],en:["Internal DNS IP","Any random IP","Broadcast address"]},a:0}
];

function card(icon,title,text){return `<article class="info-card"><span>${icon}</span><h3>${title}</h3><p>${text}</p></article>`}
function render(){const s=slides[step];app.innerHTML=`<div class="kp-shell"><header class="kp-header"><button onclick="goDashboard()">← Dashboard</button><div class="kp-progress"><i style="width:${((step+1)/slides.length)*100}%"></i></div><span>${step+1}/${slides.length}</span></header><section class="card kp-stage"><span class="kp-chip">KP07</span><div class="kp-hero-icon">${s.icon}</div><h1>${s.title[lang]}</h1><p class="kp-lead">${s.lead[lang]}</p>${s.lab?renderLab():s.activity?renderActivity():s.quiz?renderQuiz():s.body()}<div id="feedback" class="feedback"></div><div class="kp-nav"><button class="secondary" onclick="previous()" ${step===0?"disabled":""}>← ${lang==="ms"?"Sebelumnya":"Previous"}</button><button onclick="next()">${step===slides.length-1?(lang==="ms"?"SELESAIKAN KP":"COMPLETE KP"):(lang==="ms"?"Seterusnya":"Next")} →</button></div></section></div>`}
function renderLab(){const steps=["DNS Manager","New Zone","Zone Type","Zone Name","New Host (A)","Host Data","nslookup Test"];return `<div class="lab-window"><div class="lab-titlebar"><b>DNS Manager</b><span>— □ ×</span></div><div class="lab-body"><aside class="lab-sidebar">${steps.map((x,i)=>`<button class="${i===labStep?"active":""}">${i+1}. ${x}</button>`).join("")}</aside><section class="lab-content"><h2>${steps[labStep]}</h2><div class="lab-panel">${labControls()}<div id="labStatus" class="lab-status">${lang==="ms"?"Langkah "+(labStep+1)+" daripada "+steps.length:"Step "+(labStep+1)+" of "+steps.length}</div></div></section></div></div>`}
function labControls(){switch(labStep){case 0:return `<p>${lang==="ms"?"Buka Tools → DNS.":"Open Tools → DNS."}</p><div class="lab-options"><button class="lab-option" onclick="advanceLab()">Tools → DNS</button><button class="lab-option" onclick="labWrong()">Tools → Print Management</button></div>`;case 1:return `<p>${lang==="ms"?"Klik kanan Forward Lookup Zones dan pilih New Zone.":"Right-click Forward Lookup Zones and choose New Zone."}</p><div class="lab-options"><button class="lab-option" onclick="advanceLab()">Forward Lookup Zones → New Zone</button></div>`;case 2:return `<p>${lang==="ms"?"Pilih Primary Zone.":"Choose Primary Zone."}</p><div class="lab-options"><button class="lab-option" onclick="advanceLab()">Primary Zone</button><button class="lab-option" onclick="labWrong()">Stub Zone</button></div>`;case 3:return `<label>Zone name</label><input id="zoneInput" class="lab-input" placeholder="serverhero.local"><div class="lab-actions"><button onclick="checkZone()">Next</button></div>`;case 4:return `<p>${lang==="ms"?"Klik kanan zon dan pilih New Host (A or AAAA).":"Right-click the zone and choose New Host (A or AAAA)."}</p><div class="lab-options"><button class="lab-option" onclick="advanceLab()">New Host (A or AAAA)</button></div>`;case 5:return `<label>Host name</label><input id="hostInput" class="lab-input" placeholder="dc01"><label>IP address</label><input id="ipInput" class="lab-input" placeholder="192.168.10.10"><div class="lab-actions"><button onclick="checkHost()">Add Host</button></div>`;default:return `<p>nslookup dc01.serverhero.local</p><div class="lab-options"><button class="lab-option" onclick="finishLab()">Run nslookup</button></div>`}}
function advanceLab(){labStep++;SHV5?.sound?.("correct");render()}
function labWrong(){SHV5?.sound?.("wrong");const e=document.getElementById("labStatus");if(e){e.textContent=lang==="ms"?"Pilihan salah. Cuba lagi.":"Incorrect option. Try again.";e.classList.add("error")}}
function checkZone(){const v=document.getElementById("zoneInput").value.trim().toLowerCase();if(v==="serverhero.local"){lab.zoneName=v;labStep++;render()}else labWrong()}
function checkHost(){const h=document.getElementById("hostInput").value.trim().toLowerCase(),ip=document.getElementById("ipInput").value.trim();if(h==="dc01"&&ip==="192.168.10.10"){lab.hostName=h;lab.ip=ip;labStep++;render()}else labWrong()}
function finishLab(){lab.tested=true;feedback(lang==="ms"?"DNS berjaya! dc01.serverhero.local → 192.168.10.10":"DNS success! dc01.serverhero.local → 192.168.10.10","good");SHV5?.sound?.("complete")}
function renderActivity(){const shuffled=[...pairs.map((p,i)=>({i,text:p.r[lang]}))].sort(()=>Math.random()-.5);return `<div class="activity-board"><div class="activity-col">${pairs.map((p,i)=>`<button class="match-btn ${matched.has(i)?"matched":""}" data-left="${i}" onclick="pickLeft(${i},this)">${p.l[lang]}</button>`).join("")}</div><div class="activity-col">${shuffled.map(x=>`<button class="match-btn ${matched.has(x.i)?"matched":""}" data-right="${x.i}" onclick="pickRight(${x.i},this)">${x.text}</button>`).join("")}</div></div>`}
function pickLeft(i,b){if(matched.has(i))return;selectedLeft=i;document.querySelectorAll("[data-left]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}
function pickRight(i,b){if(selectedLeft===null)return;if(i===selectedLeft){matched.add(i);document.querySelector(`[data-left="${i}"]`)?.classList.add("matched");b.classList.add("matched");selectedLeft=null;feedback(lang==="ms"?"Padanan betul!":"Correct match!","good")}else feedback(lang==="ms"?"Belum tepat. Cuba lagi.":"Not correct yet. Try again.","bad")}
function renderQuiz(){return `<div class="quiz-list">${quiz.map((q,qi)=>`<article class="quiz-card"><h3>${qi+1}. ${q.q[lang]}</h3>${q.o[lang].map((o,oi)=>`<button class="quiz-option ${answers[qi]===oi?"selected":""}" onclick="answer(${qi},${oi},this)">${String.fromCharCode(65+oi)}. ${o}</button>`).join("")}</article>`).join("")}</div>`}
function answer(q,o,b){answers[q]=o;document.querySelectorAll(`.quiz-card:nth-child(${q+1}) .quiz-option`).forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}
function feedback(text,type){const e=document.getElementById("feedback");if(e){e.textContent=text;e.className="feedback "+type}}
function previous(){if(step>0){step--;render()}}
function next(){if(slides[step].lab&&!lab.tested){feedback(lang==="ms"?"Lengkapkan Virtual Lab dahulu.":"Complete the Virtual Lab first.","bad");return}if(slides[step].activity&&matched.size<pairs.length){feedback(lang==="ms"?"Lengkapkan semua padanan dahulu.":"Complete all matches first.","bad");return}if(slides[step].quiz){if(Object.keys(answers).length<quiz.length){feedback(lang==="ms"?"Jawab semua soalan dahulu.":"Answer all questions first.","bad");return}complete();return}if(step<slides.length-1){step++;render()}}
function complete(){let correct=0;quiz.forEach((q,i)=>{if(answers[i]===q.a)correct++});const score=Math.round(correct/quiz.length*100);state.completedKP=state.completedKP||[];const first=!state.completedKP.includes(7);if(first)state.completedKP.push(7);state.unlocked=Math.max(state.unlocked||7,8);state.badges=state.badges||[];if(first){state.xp=(state.xp||0)+270+(correct*15);state.coins=(state.coins||0)+170;if(!state.badges.includes("dns-specialist"))state.badges.push("dns-specialist")}SHStorage.save(state);SHV5?.sound?.("complete");app.innerHTML=`<section class="center"><div class="card hero"><div class="complete-icon">🌐</div><h1>DNS Specialist!</h1><div class="score-ring" style="--score:${score*3.6}deg"><b>${score}%</b></div><p>${lang==="ms"?"KP07 selesai dan KP08 telah dibuka.":"KP07 is complete and KP08 has been unlocked."}</p><p><strong>${first?`+${270+(correct*15)} XP · +170 Coin · Badge DNS Specialist`:(lang==="ms"?"Ganjaran telah dituntut sebelum ini.":"Reward was claimed previously.")}</strong></p><button class="primary" onclick="goDashboard()">Dashboard</button></div></section>`}
function goDashboard(){window.location.href="index.html"}
render();
