const app=document.getElementById("kpApp");
let state=SHStorage.load();
const lang=state.lang||"ms";
let step=0,labStep=0,selectedLeft=null;
const matched=new Set();
let answers={};
let lab={scope:"",start:"",end:"",mask:"",gateway:"",dns:"",active:false,tested:false};

const slides=[
{icon:"📡",title:{ms:"Misi KP08: Konfigurasi DHCP",en:"KP08 Mission: DHCP Configuration"},lead:{ms:"Konfigurasikan DHCP supaya klien menerima alamat IP secara automatik.",en:"Configure DHCP so clients receive IP addresses automatically."},body:()=>`<div class="story-alert"><strong>🚨 Mission Briefing</strong>${lang==="ms"?"Komputer klien tidak menerima alamat IP. Anda perlu memasang dan mengkonfigurasi DHCP sebelum makmal boleh digunakan.":"Client computers are not receiving IP addresses. You must install and configure DHCP before the lab can be used."}</div><div class="card-grid three">${card("🧠",lang==="ms"?"Objektif 1":"Objective 1",lang==="ms"?"Memahami fungsi DHCP dan proses DORA.":"Understand DHCP and the DORA process.")}${card("🗂️",lang==="ms"?"Objektif 2":"Objective 2",lang==="ms"?"Mencipta scope dan menetapkan pilihan rangkaian.":"Create a scope and configure network options.")}${card("🔍",lang==="ms"?"Objektif 3":"Objective 3",lang==="ms"?"Menguji klien menggunakan ipconfig /renew.":"Test the client using ipconfig /renew.")}</div>`},
{icon:"🔄",title:{ms:"Proses DORA",en:"The DORA Process"},lead:{ms:"DHCP menggunakan empat langkah untuk memberikan alamat IP kepada klien.",en:"DHCP uses four steps to assign an IP address to a client."},body:()=>`<div class="card-grid two">${card("📣","Discover",lang==="ms"?"Klien mencari DHCP Server.":"The client searches for a DHCP server.")}${card("🎁","Offer",lang==="ms"?"Server menawarkan alamat IP.":"The server offers an IP address.")}${card("🙋","Request",lang==="ms"?"Klien meminta alamat yang ditawarkan.":"The client requests the offered address.")}${card("✅","Acknowledge",lang==="ms"?"Server mengesahkan lease.":"The server confirms the lease.")}</div>`},
{icon:"🧩",title:{ms:"Komponen DHCP",en:"DHCP Components"},lead:{ms:"Scope dan pilihan DHCP menentukan cara klien menerima konfigurasi rangkaian.",en:"Scopes and DHCP options determine how clients receive network configuration."},body:()=>`<div class="card-grid three">${card("📍",lang==="ms"?"Scope":"Scope",lang==="ms"?"Julat alamat IP yang boleh diberikan.":"The range of IP addresses that may be assigned.")}${card("🚫",lang==="ms"?"Exclusion":"Exclusion",lang==="ms"?"Alamat dalam scope yang tidak boleh diberikan.":"Addresses in the scope that must not be assigned.")}${card("📌",lang==="ms"?"Reservation":"Reservation",lang==="ms"?"Alamat tetap berdasarkan MAC address.":"A fixed address based on a MAC address.")}${card("⏳",lang==="ms"?"Lease":"Lease",lang==="ms"?"Tempoh alamat IP dipinjamkan kepada klien.":"The period for which an IP address is assigned.")}${card("🚪",lang==="ms"?"Gateway":"Gateway",lang==="ms"?"Laluan keluar ke rangkaian lain.":"The route to other networks.")}${card("🌐","DNS",lang==="ms"?"Server untuk resolusi nama.":"The server used for name resolution.")}</div>`},
{icon:"🖥️",title:{ms:"Virtual Lab: DHCP Manager",en:"Virtual Lab: DHCP Manager"},lead:{ms:"Pasang role, authorize server, cipta scope dan uji klien.",en:"Install the role, authorise the server, create a scope and test a client."},lab:true},
{icon:"🧯",title:{ms:"Penyelesaian Masalah DHCP",en:"DHCP Troubleshooting"},lead:{ms:"Semak servis, authorization, scope dan sambungan rangkaian.",en:"Check the service, authorisation, scope and network connection."},body:()=>`<div class="card-grid two">${card("🟢",lang==="ms"?"Scope Active":"Scope Active",lang==="ms"?"Pastikan scope telah diaktifkan.":"Ensure the scope is activated.")}${card("✅",lang==="ms"?"Authorized":"Authorised",lang==="ms"?"Pastikan DHCP Server telah di-authorize.":"Ensure the DHCP server is authorised.")}${card("📊",lang==="ms"?"Available Addresses":"Available Addresses",lang==="ms"?"Pastikan masih ada alamat yang boleh diberikan.":"Ensure addresses are still available.")}${card("🔄","ipconfig /renew",lang==="ms"?"Minta konfigurasi baharu daripada DHCP Server.":"Request a new configuration from the DHCP server.")}</div>`},
{icon:"🎮",title:{ms:"Aktiviti Padanan DHCP",en:"DHCP Matching Activity"},lead:{ms:"Padankan istilah DHCP dengan fungsinya.",en:"Match each DHCP term with its function."},activity:true},
{icon:"🧠",title:{ms:"Kuiz KP08",en:"KP08 Quiz"},lead:{ms:"Jawab semua 10 soalan untuk menamatkan KP08.",en:"Answer all 10 questions to complete KP08."},quiz:true}
];

const pairs=[
{l:{ms:"Scope",en:"Scope"},r:{ms:"Julat alamat IP",en:"Range of IP addresses"}},
{l:{ms:"Exclusion",en:"Exclusion"},r:{ms:"Alamat yang tidak boleh diberikan",en:"Addresses that must not be assigned"}},
{l:{ms:"Reservation",en:"Reservation"},r:{ms:"Alamat tetap berdasarkan MAC",en:"Fixed address based on MAC"}},
{l:{ms:"Lease",en:"Lease"},r:{ms:"Tempoh penggunaan alamat IP",en:"Duration of IP address use"}}
];

const quiz=[
{q:{ms:"Apakah fungsi DHCP?",en:"What is the function of DHCP?"},o:{ms:["Memberi IP secara automatik","Menyimpan e-mel","Mengawal suhu"],en:["Assign IP addresses automatically","Store email","Control temperature"]},a:0},
{q:{ms:"D dalam DORA bermaksud?",en:"What does D in DORA mean?"},o:{ms:["Discover","Domain","Download"],en:["Discover","Domain","Download"]},a:0},
{q:{ms:"Apakah scope?",en:"What is a scope?"},o:{ms:["Julat IP untuk klien","Nama domain","Jenis RAID"],en:["IP range for clients","Domain name","RAID type"]},a:0},
{q:{ms:"Apakah exclusion?",en:"What is an exclusion?"},o:{ms:["Alamat yang tidak diberi","Alamat gateway","Alamat DNS"],en:["An address not assigned","Gateway address","DNS address"]},a:0},
{q:{ms:"Apakah reservation?",en:"What is a reservation?"},o:{ms:["IP tetap berdasarkan MAC","IP rawak","Nama host"],en:["Fixed IP based on MAC","Random IP","Host name"]},a:0},
{q:{ms:"Apakah lease?",en:"What is a lease?"},o:{ms:["Tempoh penggunaan IP","Nama server","Kata laluan"],en:["IP usage period","Server name","Password"]},a:0},
{q:{ms:"Mengapa DHCP Server perlu authorize?",en:"Why must a DHCP server be authorised?"},o:{ms:["Supaya boleh memberi IP dalam domain","Untuk format disk","Untuk shutdown"],en:["So it can assign IPs in the domain","To format a disk","To shut down"]},a:0},
{q:{ms:"Arahan untuk minta IP baharu?",en:"Which command requests a new IP?"},o:{ms:["ipconfig /renew","nslookup","format"],en:["ipconfig /renew","nslookup","format"]},a:0},
{q:{ms:"Gateway digunakan untuk?",en:"What is the gateway used for?"},o:{ms:["Akses rangkaian lain","Simpan pengguna","Uji RAM"],en:["Access other networks","Store users","Test RAM"]},a:0},
{q:{ms:"DNS option memberi?",en:"What does the DNS option provide?"},o:{ms:["Alamat DNS Server","Alamat MAC","Nama pengguna"],en:["DNS server address","MAC address","Username"]},a:0}
];

function card(icon,title,text){return `<article class="info-card"><span>${icon}</span><h3>${title}</h3><p>${text}</p></article>`}
function render(){const s=slides[step];app.innerHTML=`<div class="kp-shell"><header class="kp-header"><button onclick="goDashboard()">← Dashboard</button><div class="kp-progress"><i style="width:${((step+1)/slides.length)*100}%"></i></div><span>${step+1}/${slides.length}</span></header><section class="card kp-stage"><span class="kp-chip">KP08</span><div class="kp-hero-icon">${s.icon}</div><h1>${s.title[lang]}</h1><p class="kp-lead">${s.lead[lang]}</p>${s.lab?renderLab():s.activity?renderActivity():s.quiz?renderQuiz():s.body()}<div id="feedback" class="feedback"></div><div class="kp-nav"><button class="secondary" onclick="previous()" ${step===0?"disabled":""}>← ${lang==="ms"?"Sebelumnya":"Previous"}</button><button onclick="next()">${step===slides.length-1?(lang==="ms"?"SELESAIKAN KP":"COMPLETE KP"):(lang==="ms"?"Seterusnya":"Next")} →</button></div></section></div>`}
function renderLab(){const steps=["Install Role","Authorize","New Scope","IP Range","Subnet Mask","Gateway","DNS","Activate","Client Test"];return `<div class="lab-window"><div class="lab-titlebar"><b>DHCP Manager</b><span>— □ ×</span></div><div class="lab-body"><aside class="lab-sidebar">${steps.map((x,i)=>`<button class="${i===labStep?"active":""}">${i+1}. ${x}</button>`).join("")}</aside><section class="lab-content"><h2>${steps[labStep]}</h2><div class="lab-panel">${labControls()}<div id="labStatus" class="lab-status">${lang==="ms"?"Langkah "+(labStep+1)+" daripada "+steps.length:"Step "+(labStep+1)+" of "+steps.length}</div></div></section></div></div>`}
function labControls(){switch(labStep){
case 0:return `<p>${lang==="ms"?"Pilih role DHCP Server dan klik Install.":"Select the DHCP Server role and click Install."}</p><div class="lab-options"><button class="lab-option" onclick="advanceLab()">☑ DHCP Server → Install</button><button class="lab-option" onclick="labWrong()">☐ Print Services</button></div>`;
case 1:return `<p>${lang==="ms"?"Authorize DHCP Server dalam domain.":"Authorise the DHCP server in the domain."}</p><div class="lab-options"><button class="lab-option" onclick="advanceLab()">Authorize</button><button class="lab-option" onclick="labWrong()">Unauthorize</button></div>`;
case 2:return `<label>Scope name</label><input id="scopeInput" class="lab-input" placeholder="LAB-SCOPE"><div class="lab-actions"><button onclick="checkScope()">Next</button></div>`;
case 3:return `<label>Start IP</label><input id="startInput" class="lab-input" placeholder="192.168.10.100"><label>End IP</label><input id="endInput" class="lab-input" placeholder="192.168.10.200"><div class="lab-actions"><button onclick="checkRange()">Next</button></div>`;
case 4:return `<label>Subnet Mask</label><input id="maskInput" class="lab-input" placeholder="255.255.255.0"><div class="lab-actions"><button onclick="checkMask()">Next</button></div>`;
case 5:return `<label>Default Gateway</label><input id="gwInput" class="lab-input" placeholder="192.168.10.1"><div class="lab-actions"><button onclick="checkGateway()">Next</button></div>`;
case 6:return `<label>DNS Server</label><input id="dnsInput" class="lab-input" placeholder="192.168.10.10"><div class="lab-actions"><button onclick="checkDNS()">Next</button></div>`;
case 7:return `<p>${lang==="ms"?"Aktifkan scope.":"Activate the scope."}</p><div class="lab-options"><button class="lab-option" onclick="activateScope()">Activate this scope</button></div>`;
default:return `<p>ipconfig /renew</p><div class="lab-options"><button class="lab-option" onclick="finishLab()">Run Client Test</button></div>`;
}}
function advanceLab(){labStep++;SHV5?.sound?.("correct");render()}
function labWrong(){SHV5?.sound?.("wrong");const e=document.getElementById("labStatus");if(e){e.textContent=lang==="ms"?"Pilihan salah. Cuba lagi.":"Incorrect option. Try again.";e.classList.add("error")}}
function checkScope(){const v=document.getElementById("scopeInput").value.trim();if(v.toUpperCase()==="LAB-SCOPE"){lab.scope=v;labStep++;render()}else labWrong()}
function checkRange(){const a=document.getElementById("startInput").value.trim(),b=document.getElementById("endInput").value.trim();if(a==="192.168.10.100"&&b==="192.168.10.200"){lab.start=a;lab.end=b;labStep++;render()}else labWrong()}
function checkMask(){const v=document.getElementById("maskInput").value.trim();if(v==="255.255.255.0"){lab.mask=v;labStep++;render()}else labWrong()}
function checkGateway(){const v=document.getElementById("gwInput").value.trim();if(v==="192.168.10.1"){lab.gateway=v;labStep++;render()}else labWrong()}
function checkDNS(){const v=document.getElementById("dnsInput").value.trim();if(v==="192.168.10.10"){lab.dns=v;labStep++;render()}else labWrong()}
function activateScope(){lab.active=true;labStep++;render()}
function finishLab(){lab.tested=true;feedback(lang==="ms"?"DHCP berjaya! Klien menerima 192.168.10.100":"DHCP success! The client received 192.168.10.100","good");SHV5?.sound?.("complete")}
function renderActivity(){const shuffled=[...pairs.map((p,i)=>({i,text:p.r[lang]}))].sort(()=>Math.random()-.5);return `<div class="activity-board"><div class="activity-col">${pairs.map((p,i)=>`<button class="match-btn ${matched.has(i)?"matched":""}" data-left="${i}" onclick="pickLeft(${i},this)">${p.l[lang]}</button>`).join("")}</div><div class="activity-col">${shuffled.map(x=>`<button class="match-btn ${matched.has(x.i)?"matched":""}" data-right="${x.i}" onclick="pickRight(${x.i},this)">${x.text}</button>`).join("")}</div></div>`}
function pickLeft(i,b){if(matched.has(i))return;selectedLeft=i;document.querySelectorAll("[data-left]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}
function pickRight(i,b){if(selectedLeft===null)return;if(i===selectedLeft){matched.add(i);document.querySelector(`[data-left="${i}"]`)?.classList.add("matched");b.classList.add("matched");selectedLeft=null;feedback(lang==="ms"?"Padanan betul!":"Correct match!","good")}else feedback(lang==="ms"?"Belum tepat. Cuba lagi.":"Not correct yet. Try again.","bad")}
function renderQuiz(){return `<div class="quiz-list">${quiz.map((q,qi)=>`<article class="quiz-card"><h3>${qi+1}. ${q.q[lang]}</h3>${q.o[lang].map((o,oi)=>`<button class="quiz-option ${answers[qi]===oi?"selected":""}" onclick="answer(${qi},${oi},this)">${String.fromCharCode(65+oi)}. ${o}</button>`).join("")}</article>`).join("")}</div>`}
function answer(q,o,b){answers[q]=o;document.querySelectorAll(`.quiz-card:nth-child(${q+1}) .quiz-option`).forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}
function feedback(text,type){const e=document.getElementById("feedback");if(e){e.textContent=text;e.className="feedback "+type}}
function previous(){if(step>0){step--;render()}}
function next(){if(slides[step].lab&&!lab.tested){feedback(lang==="ms"?"Lengkapkan Virtual Lab dahulu.":"Complete the Virtual Lab first.","bad");return}if(slides[step].activity&&matched.size<pairs.length){feedback(lang==="ms"?"Lengkapkan semua padanan dahulu.":"Complete all matches first.","bad");return}if(slides[step].quiz){if(Object.keys(answers).length<quiz.length){feedback(lang==="ms"?"Jawab semua soalan dahulu.":"Answer all questions first.","bad");return}complete();return}if(step<slides.length-1){step++;render()}}
function complete(){let correct=0;quiz.forEach((q,i)=>{if(answers[i]===q.a)correct++});const score=Math.round(correct/quiz.length*100);state.completedKP=state.completedKP||[];const first=!state.completedKP.includes(8);if(first)state.completedKP.push(8);state.unlocked=Math.max(state.unlocked||8,9);state.badges=state.badges||[];if(first){state.xp=(state.xp||0)+290+(correct*15);state.coins=(state.coins||0)+190;if(!state.badges.includes("dhcp-specialist"))state.badges.push("dhcp-specialist")}SHStorage.save(state);SHV5?.sound?.("complete");app.innerHTML=`<section class="center"><div class="card hero"><div class="complete-icon">📡</div><h1>DHCP Specialist!</h1><div class="score-ring" style="--score:${score*3.6}deg"><b>${score}%</b></div><p>${lang==="ms"?"KP08 selesai dan KP09 telah dibuka.":"KP08 is complete and KP09 has been unlocked."}</p><p><strong>${first?`+${290+(correct*15)} XP · +190 Coin · Badge DHCP Specialist`:(lang==="ms"?"Ganjaran telah dituntut sebelum ini.":"Reward was claimed previously.")}</strong></p><button class="primary" onclick="goDashboard()">Dashboard</button></div></section>`}
function goDashboard(){window.location.href="index.html"}
render();
