const app=document.getElementById("kpApp");
let state=SHStorage.load();
const lang=state.lang||"ms";
let step=0,labStep=0,selectedLeft=null;
const matched=new Set();
let answers={};
let lab={ou:false,user:false,group:false,member:false,reset:false,unlock:false,tested:false};

const slides=[
{icon:"👥",title:{ms:"Misi KP09: Pengurusan Pengguna dan Kumpulan",en:"KP09 Mission: User and Group Management"},lead:{ms:"Urus akaun pengguna, OU dan kumpulan dalam domain serverhero.local.",en:"Manage user accounts, OUs and groups in the serverhero.local domain."},body:()=>`<div class="story-alert"><strong>🚨 Mission Briefing</strong>${lang==="ms"?"Pekerja baharu telah melapor diri. Anda perlu mencipta OU, akaun pengguna dan kumpulan keselamatan sebelum akses diberikan.":"New staff members have arrived. You must create an OU, user account and security group before access is granted."}</div><div class="card-grid three">${card("📁",lang==="ms"?"Objektif 1":"Objective 1",lang==="ms"?"Mencipta dan mengurus Organizational Unit.":"Create and manage an Organizational Unit.")}${card("👤",lang==="ms"?"Objektif 2":"Objective 2",lang==="ms"?"Mencipta akaun pengguna dan menetapkan kata laluan.":"Create user accounts and configure passwords.")}${card("👥",lang==="ms"?"Objektif 3":"Objective 3",lang==="ms"?"Mencipta kumpulan keselamatan dan menambah ahli.":"Create a security group and add members.")}</div>`},
{icon:"📁",title:{ms:"OU, User dan Group",en:"OU, User and Group"},lead:{ms:"Objek Active Directory digunakan untuk menyusun dan mengawal akses secara berpusat.",en:"Active Directory objects are used to organise and control access centrally."},body:()=>`<div class="card-grid three">${card("📁","OU",lang==="ms"?"Bekas untuk menyusun pengguna, komputer dan kumpulan.":"A container used to organise users, computers and groups.")}${card("👤","User",lang==="ms"?"Akaun individu untuk login dan akses sumber.":"An individual account for sign-in and resource access.")}${card("👥","Group",lang==="ms"?"Kumpulan akaun untuk pemberian kebenaran secara mudah.":"A collection of accounts for easier permission assignment.")}</div>`},
{icon:"🔐",title:{ms:"Keselamatan Akaun",en:"Account Security"},lead:{ms:"Polisi kata laluan dan status akaun membantu mengurangkan risiko keselamatan.",en:"Password policies and account status help reduce security risks."},body:()=>`<div class="card-grid two">${card("🔑",lang==="ms"?"Kata Laluan Kukuh":"Strong Password",lang==="ms"?"Gunakan gabungan huruf, nombor dan simbol.":"Use a combination of letters, numbers and symbols.")}${card("🔄",lang==="ms"?"Must Change Password":"Must Change Password",lang==="ms"?"Memaksa pengguna menukar kata laluan pada login pertama.":"Forces the user to change the password at first sign-in.")}${card("🔒",lang==="ms"?"Account Locked":"Account Locked",lang==="ms"?"Akaun boleh dikunci selepas percubaan login gagal.":"The account may lock after failed sign-in attempts.")}${card("⛔",lang==="ms"?"Disable Account":"Disable Account",lang==="ms"?"Menghalang login tanpa memadam akaun.":"Prevents sign-in without deleting the account.")}</div>`},
{icon:"🖥️",title:{ms:"Virtual Lab: AD Users and Computers",en:"Virtual Lab: AD Users and Computers"},lead:{ms:"Cipta OU STAFF, pengguna Ali Ahmad dan kumpulan IT-STAFF.",en:"Create the STAFF OU, the Ali Ahmad user and the IT-STAFF group."},lab:true},
{icon:"🧯",title:{ms:"Penyelesaian Masalah Akaun",en:"Account Troubleshooting"},lead:{ms:"Semak status akaun, kata laluan dan keahlian kumpulan apabila pengguna gagal login.",en:"Check account status, password and group membership when a user cannot sign in."},body:()=>`<div class="card-grid two">${card("🔓",lang==="ms"?"Unlock Account":"Unlock Account",lang==="ms"?"Buka kunci selepas terlalu banyak percubaan gagal.":"Unlock after too many failed attempts.")}${card("🔁",lang==="ms"?"Reset Password":"Reset Password",lang==="ms"?"Tetapkan kata laluan baharu apabila pengguna terlupa.":"Set a new password when the user forgets it.")}${card("✅",lang==="ms"?"Enable Account":"Enable Account",lang==="ms"?"Aktifkan semula akaun yang dinyahaktifkan.":"Re-enable a disabled account.")}${card("👥",lang==="ms"?"Group Membership":"Group Membership",lang==="ms"?"Semak sama ada pengguna berada dalam kumpulan yang betul.":"Check whether the user belongs to the correct group.")}</div>`},
{icon:"🎮",title:{ms:"Aktiviti Padanan",en:"Matching Activity"},lead:{ms:"Padankan objek Active Directory dengan fungsinya.",en:"Match each Active Directory object with its function."},activity:true},
{icon:"🧠",title:{ms:"Kuiz KP09",en:"KP09 Quiz"},lead:{ms:"Jawab semua 10 soalan untuk menamatkan KP09.",en:"Answer all 10 questions to complete KP09."},quiz:true}
];

const pairs=[
{l:{ms:"OU",en:"OU"},r:{ms:"Bekas untuk menyusun objek",en:"Container used to organise objects"}},
{l:{ms:"User",en:"User"},r:{ms:"Akaun individu",en:"Individual account"}},
{l:{ms:"Group",en:"Group"},r:{ms:"Kumpulan pengguna untuk kebenaran",en:"Collection of users for permissions"}},
{l:{ms:"Reset Password",en:"Reset Password"},r:{ms:"Tetapkan kata laluan baharu",en:"Set a new password"}}
];

const quiz=[
{q:{ms:"Apakah fungsi OU?",en:"What is the function of an OU?"},o:{ms:["Menyusun objek AD","Memberi alamat IP","Menyimpan backup"],en:["Organise AD objects","Assign IP addresses","Store backups"]},a:0},
{q:{ms:"Apakah user account?",en:"What is a user account?"},o:{ms:["Akaun individu untuk login","Nama zon DNS","Jenis kabel"],en:["Individual sign-in account","DNS zone name","Cable type"]},a:0},
{q:{ms:"Apakah fungsi group?",en:"What is the function of a group?"},o:{ms:["Memudahkan pemberian kebenaran","Menaikkan suhu server","Memformat cakera"],en:["Simplify permission assignment","Increase server temperature","Format a disk"]},a:0},
{q:{ms:"Group type untuk kebenaran ialah?",en:"Which group type is used for permissions?"},o:{ms:["Security","Distribution sahaja","Temporary"],en:["Security","Distribution only","Temporary"]},a:0},
{q:{ms:"Apakah user logon name dalam lab?",en:"What is the user logon name in the lab?"},o:{ms:["ali","ahmad","staff"],en:["ali","ahmad","staff"]},a:0},
{q:{ms:"Nama OU dalam lab?",en:"What is the OU name in the lab?"},o:{ms:["STAFF","USERS","LAB"],en:["STAFF","USERS","LAB"]},a:0},
{q:{ms:"Nama kumpulan dalam lab?",en:"What is the group name in the lab?"},o:{ms:["IT-STAFF","ALL-USERS","SERVER"],en:["IT-STAFF","ALL-USERS","SERVER"]},a:0},
{q:{ms:"Reset Password digunakan apabila?",en:"When is Reset Password used?"},o:{ms:["Pengguna terlupa kata laluan","IP tidak diterima","DNS gagal"],en:["A user forgets a password","An IP is not received","DNS fails"]},a:0},
{q:{ms:"Unlock Account digunakan apabila?",en:"When is Unlock Account used?"},o:{ms:["Akaun dikunci","Cakera penuh","Server panas"],en:["The account is locked","The disk is full","The server is hot"]},a:0},
{q:{ms:"Disable Account bermaksud?",en:"What does Disable Account mean?"},o:{ms:["Menghalang login tanpa memadam akaun","Memadam akaun terus","Menukar nama domain"],en:["Prevent sign-in without deleting the account","Delete the account immediately","Change the domain name"]},a:0}
];

function card(icon,title,text){return `<article class="info-card"><span>${icon}</span><h3>${title}</h3><p>${text}</p></article>`}
function render(){const s=slides[step];app.innerHTML=`<div class="kp-shell"><header class="kp-header"><button onclick="goDashboard()">← Dashboard</button><div class="kp-progress"><i style="width:${((step+1)/slides.length)*100}%"></i></div><span>${step+1}/${slides.length}</span></header><section class="card kp-stage"><span class="kp-chip">KP09</span><div class="kp-hero-icon">${s.icon}</div><h1>${s.title[lang]}</h1><p class="kp-lead">${s.lead[lang]}</p>${s.lab?renderLab():s.activity?renderActivity():s.quiz?renderQuiz():s.body()}<div id="feedback" class="feedback"></div><div class="kp-nav"><button class="secondary" onclick="previous()" ${step===0?"disabled":""}>← ${lang==="ms"?"Sebelumnya":"Previous"}</button><button onclick="next()">${step===slides.length-1?(lang==="ms"?"SELESAIKAN KP":"COMPLETE KP"):(lang==="ms"?"Seterusnya":"Next")} →</button></div></section></div>`}
function renderLab(){const steps=["Open ADUC","Create OU","Create User","Password Options","Create Group","Add Member","Reset Password","Unlock Account","Verification"];return `<div class="lab-window"><div class="lab-titlebar"><b>Active Directory Users and Computers</b><span>— □ ×</span></div><div class="lab-body"><aside class="lab-sidebar">${steps.map((x,i)=>`<button class="${i===labStep?"active":""}">${i+1}. ${x}</button>`).join("")}</aside><section class="lab-content"><h2>${steps[labStep]}</h2><div class="lab-panel">${labControls()}<div id="labStatus" class="lab-status">${lang==="ms"?"Langkah "+(labStep+1)+" daripada "+steps.length:"Step "+(labStep+1)+" of "+steps.length}</div></div></section></div></div>`}
function labControls(){switch(labStep){
case 0:return `<p>${lang==="ms"?"Buka Tools → Active Directory Users and Computers.":"Open Tools → Active Directory Users and Computers."}</p><div class="lab-options"><button class="lab-option" onclick="advanceLab()">Tools → Active Directory Users and Computers</button><button class="lab-option" onclick="labWrong()">Tools → DNS</button></div>`;
case 1:return `<label>OU Name</label><input id="ouInput" class="lab-input" placeholder="STAFF"><div class="lab-actions"><button onclick="checkOU()">Create OU</button></div>`;
case 2:return `<label>First Name</label><input id="firstInput" class="lab-input" placeholder="Ali"><label>Last Name</label><input id="lastInput" class="lab-input" placeholder="Ahmad"><label>User Logon Name</label><input id="logonInput" class="lab-input" placeholder="ali"><div class="lab-actions"><button onclick="checkUser()">Next</button></div>`;
case 3:return `<label>Password</label><input id="passInput" type="password" class="lab-input" placeholder="Server@123"><label class="lab-check"><input id="mustChange" type="checkbox"> User must change password at next logon</label><div class="lab-actions"><button onclick="checkPassword()">Create User</button></div>`;
case 4:return `<label>Group Name</label><input id="groupInput" class="lab-input" placeholder="IT-STAFF"><div class="lab-options"><button class="lab-option" onclick="checkGroup()">Global · Security</button><button class="lab-option" onclick="labWrong()">Universal · Distribution</button></div>`;
case 5:return `<p>${lang==="ms"?"Tambah pengguna ali ke kumpulan IT-STAFF.":"Add user ali to the IT-STAFF group."}</p><div class="lab-options"><button class="lab-option" onclick="addMember()">Add ali to IT-STAFF</button></div>`;
case 6:return `<label>New Password</label><input id="resetInput" type="password" class="lab-input" placeholder="Server@12345"><div class="lab-actions"><button onclick="resetPassword()">Reset Password</button></div>`;
case 7:return `<p>${lang==="ms"?"Akaun ali dikunci. Pilih tindakan yang betul.":"The ali account is locked. Choose the correct action."}</p><div class="lab-options"><button class="lab-option" onclick="unlockAccount()">Unlock Account</button><button class="lab-option" onclick="labWrong()">Delete Account</button></div>`;
default:return `<p>${lang==="ms"?"Semak OU STAFF, pengguna ali dan kumpulan IT-STAFF.":"Verify the STAFF OU, ali user and IT-STAFF group."}</p><div class="lab-options"><button class="lab-option" onclick="finishLab()">Verify Configuration</button></div>`;
}}
function advanceLab(){labStep++;SHV5?.sound?.("correct");render()}
function labWrong(){SHV5?.sound?.("wrong");const e=document.getElementById("labStatus");if(e){e.textContent=lang==="ms"?"Pilihan salah. Cuba lagi.":"Incorrect option. Try again.";e.classList.add("error")}}
function checkOU(){const v=document.getElementById("ouInput").value.trim().toUpperCase();if(v==="STAFF"){lab.ou=true;labStep++;render()}else labWrong()}
function checkUser(){const a=document.getElementById("firstInput").value.trim().toLowerCase(),b=document.getElementById("lastInput").value.trim().toLowerCase(),c=document.getElementById("logonInput").value.trim().toLowerCase();if(a==="ali"&&b==="ahmad"&&c==="ali"){lab.user=true;labStep++;render()}else labWrong()}
function checkPassword(){const p=document.getElementById("passInput").value;const c=document.getElementById("mustChange").checked;if(p==="Server@123"&&c){labStep++;render()}else labWrong()}
function checkGroup(){const v=document.getElementById("groupInput").value.trim().toUpperCase();if(v==="IT-STAFF"){lab.group=true;labStep++;render()}else labWrong()}
function addMember(){lab.member=true;labStep++;render()}
function resetPassword(){const v=document.getElementById("resetInput").value;if(v==="Server@12345"){lab.reset=true;labStep++;render()}else labWrong()}
function unlockAccount(){lab.unlock=true;labStep++;render()}
function finishLab(){lab.tested=true;feedback(lang==="ms"?"Konfigurasi berjaya! Akaun ali kini aktif dalam kumpulan IT-STAFF.":"Configuration complete! The ali account is active in the IT-STAFF group.","good");SHV5?.sound?.("complete")}
function renderActivity(){const shuffled=[...pairs.map((p,i)=>({i,text:p.r[lang]}))].sort(()=>Math.random()-.5);return `<div class="activity-board"><div class="activity-col">${pairs.map((p,i)=>`<button class="match-btn ${matched.has(i)?"matched":""}" data-left="${i}" onclick="pickLeft(${i},this)">${p.l[lang]}</button>`).join("")}</div><div class="activity-col">${shuffled.map(x=>`<button class="match-btn ${matched.has(x.i)?"matched":""}" data-right="${x.i}" onclick="pickRight(${x.i},this)">${x.text}</button>`).join("")}</div></div>`}
function pickLeft(i,b){if(matched.has(i))return;selectedLeft=i;document.querySelectorAll("[data-left]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}
function pickRight(i,b){if(selectedLeft===null)return;if(i===selectedLeft){matched.add(i);document.querySelector(`[data-left="${i}"]`)?.classList.add("matched");b.classList.add("matched");selectedLeft=null;feedback(lang==="ms"?"Padanan betul!":"Correct match!","good")}else feedback(lang==="ms"?"Belum tepat. Cuba lagi.":"Not correct yet. Try again.","bad")}
function renderQuiz(){return `<div class="quiz-list">${quiz.map((q,qi)=>`<article class="quiz-card"><h3>${qi+1}. ${q.q[lang]}</h3>${q.o[lang].map((o,oi)=>`<button class="quiz-option ${answers[qi]===oi?"selected":""}" onclick="answer(${qi},${oi},this)">${String.fromCharCode(65+oi)}. ${o}</button>`).join("")}</article>`).join("")}</div>`}
function answer(q,o,b){answers[q]=o;document.querySelectorAll(`.quiz-card:nth-child(${q+1}) .quiz-option`).forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}
function feedback(text,type){const e=document.getElementById("feedback");if(e){e.textContent=text;e.className="feedback "+type}}
function previous(){if(step>0){step--;render()}}
function next(){if(slides[step].lab&&!lab.tested){feedback(lang==="ms"?"Lengkapkan Virtual Lab dahulu.":"Complete the Virtual Lab first.","bad");return}if(slides[step].activity&&matched.size<pairs.length){feedback(lang==="ms"?"Lengkapkan semua padanan dahulu.":"Complete all matches first.","bad");return}if(slides[step].quiz){if(Object.keys(answers).length<quiz.length){feedback(lang==="ms"?"Jawab semua soalan dahulu.":"Answer all questions first.","bad");return}complete();return}if(step<slides.length-1){step++;render()}}
function complete(){let correct=0;quiz.forEach((q,i)=>{if(answers[i]===q.a)correct++});const score=Math.round(correct/quiz.length*100);state.completedKP=state.completedKP||[];const first=!state.completedKP.includes(9);if(first)state.completedKP.push(9);state.unlocked=Math.max(state.unlocked||9,10);state.badges=state.badges||[];if(first){state.xp=(state.xp||0)+320+(correct*15);state.coins=(state.coins||0)+200;if(!state.badges.includes("user-specialist"))state.badges.push("user-specialist")}SHStorage.save(state);SHV5?.sound?.("complete");app.innerHTML=`<section class="center"><div class="card hero"><div class="complete-icon">👥</div><h1>User Management Specialist!</h1><div class="score-ring" style="--score:${score*3.6}deg"><b>${score}%</b></div><p>${lang==="ms"?"KP09 selesai dan KP10 telah dibuka.":"KP09 is complete and KP10 has been unlocked."}</p><p><strong>${first?`+${320+(correct*15)} XP · +200 Coin · Badge User Management Specialist`:(lang==="ms"?"Ganjaran telah dituntut sebelum ini.":"Reward was claimed previously.")}</strong></p><button class="primary" onclick="goDashboard()">Dashboard</button></div></section>`}
function goDashboard(){window.location.href="index.html"}
render();
