const app=document.getElementById("kpApp");
let state=SHStorage.load();
const lang=state.lang||"ms";
let step=0,labStep=0,selectedLeft=null;
const matched=new Set();
let answers={};
let lab={feature:false,once:false,type:false,destination:false,backup:false,recovery:false,tested:false};

const slides=[
{icon:"💾",title:{ms:"Misi KP10: Backup dan Pemulihan Server",en:"KP10 Mission: Server Backup and Recovery"},lead:{ms:"Lindungi data server dengan backup penuh dan lakukan pemulihan fail melalui Windows Server Backup.",en:"Protect server data with a full backup and perform file recovery using Windows Server Backup."},body:()=>`<div class="story-alert"><strong>🚨 Mission Briefing</strong>${lang==="ms"?"Satu folder penting telah terpadam. Anda perlu memastikan backup tersedia dan memulihkan data sebelum operasi organisasi terganggu.":"An important folder has been deleted. You must ensure a backup is available and restore the data before operations are disrupted."}</div><div class="card-grid three">${card("🛡️",lang==="ms"?"Objektif 1":"Objective 1",lang==="ms"?"Memahami jenis backup dan kepentingan pemulihan.":"Understand backup types and the importance of recovery.")}${card("🗄️",lang==="ms"?"Objektif 2":"Objective 2",lang==="ms"?"Melaksanakan Full Server Backup.":"Perform a Full Server Backup.")}${card("♻️",lang==="ms"?"Objektif 3":"Objective 3",lang==="ms"?"Memulihkan fail menggunakan Recovery Wizard.":"Restore files using the Recovery Wizard.")}</div>`},
{icon:"📚",title:{ms:"Jenis Backup",en:"Backup Types"},lead:{ms:"Jenis backup dipilih berdasarkan masa, ruang storan dan keperluan pemulihan.",en:"Backup type is selected based on time, storage capacity and recovery requirements."},body:()=>`<div class="card-grid three">${card("📦",lang==="ms"?"Full Backup":"Full Backup",lang==="ms"?"Menyalin semua data yang dipilih.":"Copies all selected data.")}${card("➕",lang==="ms"?"Incremental Backup":"Incremental Backup",lang==="ms"?"Menyalin perubahan sejak backup terakhir.":"Copies changes since the most recent backup.")}${card("🔁",lang==="ms"?"Differential Backup":"Differential Backup",lang==="ms"?"Menyalin perubahan sejak Full Backup terakhir.":"Copies changes since the last Full Backup.")}</div>`},
{icon:"🛡️",title:{ms:"Strategi Backup 3-2-1",en:"The 3-2-1 Backup Strategy"},lead:{ms:"Strategi 3-2-1 mengurangkan risiko kehilangan data.",en:"The 3-2-1 strategy reduces the risk of data loss."},body:()=>`<div class="card-grid three">${card("3️⃣",lang==="ms"?"3 Salinan Data":"3 Data Copies",lang==="ms"?"Satu data utama dan dua salinan backup.":"One primary copy and two backup copies.")}${card("2️⃣",lang==="ms"?"2 Jenis Media":"2 Media Types",lang==="ms"?"Simpan pada dua jenis media berbeza.":"Store copies on two different media types.")}${card("1️⃣",lang==="ms"?"1 Salinan Luar Lokasi":"1 Off-site Copy",lang==="ms"?"Simpan sekurang-kurangnya satu salinan di lokasi berasingan.":"Keep at least one copy at a separate location.")}</div>`},
{icon:"🖥️",title:{ms:"Virtual Lab: Windows Server Backup",en:"Virtual Lab: Windows Server Backup"},lead:{ms:"Pasang ciri backup, buat Full Server Backup dan pulihkan folder penting.",en:"Install the backup feature, create a Full Server Backup and restore an important folder."},lab:true},
{icon:"🧯",title:{ms:"Penyelesaian Masalah Backup",en:"Backup Troubleshooting"},lead:{ms:"Semak destinasi, ruang kosong, kebenaran dan status tugas backup.",en:"Check the destination, free space, permissions and backup task status."},body:()=>`<div class="card-grid two">${card("💽",lang==="ms"?"Ruang Storan":"Storage Space",lang==="ms"?"Pastikan destinasi mempunyai ruang yang mencukupi.":"Ensure the destination has enough free space.")}${card("🔐",lang==="ms"?"Kebenaran":"Permissions",lang==="ms"?"Pastikan akaun mempunyai hak untuk membaca dan menulis.":"Ensure the account has read and write permissions.")}${card("📋",lang==="ms"?"Backup Status":"Backup Status",lang==="ms"?"Semak mesej berjaya atau kod ralat.":"Check success messages or error codes.")}${card("🧪",lang==="ms"?"Ujian Pemulihan":"Recovery Test",lang==="ms"?"Backup belum lengkap tanpa ujian restore.":"A backup is incomplete without a restore test.")}</div>`},
{icon:"🎮",title:{ms:"Aktiviti Padanan Backup",en:"Backup Matching Activity"},lead:{ms:"Padankan istilah backup dengan fungsi yang betul.",en:"Match each backup term with its correct function."},activity:true},
{icon:"🧠",title:{ms:"Kuiz KP10",en:"KP10 Quiz"},lead:{ms:"Jawab semua 10 soalan untuk menamatkan keseluruhan SERVER HERO.",en:"Answer all 10 questions to complete SERVER HERO."},quiz:true}
];

const pairs=[
{l:{ms:"Full Backup",en:"Full Backup"},r:{ms:"Menyalin semua data dipilih",en:"Copies all selected data"}},
{l:{ms:"Incremental",en:"Incremental"},r:{ms:"Perubahan sejak backup terakhir",en:"Changes since the last backup"}},
{l:{ms:"Recovery",en:"Recovery"},r:{ms:"Memulihkan data daripada backup",en:"Restores data from a backup"}},
{l:{ms:"3-2-1",en:"3-2-1"},r:{ms:"3 salinan, 2 media, 1 luar lokasi",en:"3 copies, 2 media, 1 off-site"}}
];

const quiz=[
{q:{ms:"Apakah tujuan utama backup?",en:"What is the main purpose of backup?"},o:{ms:["Melindungi data daripada kehilangan","Menambah suhu server","Menukar nama domain"],en:["Protect data from loss","Increase server temperature","Change the domain name"]},a:0},
{q:{ms:"Full Backup menyalin?",en:"What does a Full Backup copy?"},o:{ms:["Semua data dipilih","Fail terakhir sahaja","Kata laluan sahaja"],en:["All selected data","Only the latest file","Only passwords"]},a:0},
{q:{ms:"Incremental Backup menyalin?",en:"What does an Incremental Backup copy?"},o:{ms:["Perubahan sejak backup terakhir","Semua data setiap kali","Tiada data"],en:["Changes since the last backup","All data every time","No data"]},a:0},
{q:{ms:"Strategi 3-2-1 bermaksud?",en:"What does the 3-2-1 strategy mean?"},o:{ms:["3 salinan, 2 media, 1 luar lokasi","3 server, 2 domain, 1 user","3 password, 2 admin, 1 disk"],en:["3 copies, 2 media, 1 off-site","3 servers, 2 domains, 1 user","3 passwords, 2 admins, 1 disk"]},a:0},
{q:{ms:"Ciri Windows yang digunakan?",en:"Which Windows feature is used?"},o:{ms:["Windows Server Backup","DNS Manager","DHCP Manager"],en:["Windows Server Backup","DNS Manager","DHCP Manager"]},a:0},
{q:{ms:"Destinasi backup dalam lab?",en:"What is the backup destination in the lab?"},o:{ms:["Drive E:","Drive C: sahaja","Desktop"],en:["Drive E:","Drive C: only","Desktop"]},a:0},
{q:{ms:"Recovery Wizard digunakan untuk?",en:"What is the Recovery Wizard used for?"},o:{ms:["Memulihkan fail","Mencipta user","Memberi IP"],en:["Restore files","Create a user","Assign an IP"]},a:0},
{q:{ms:"Apakah perlu dibuat selepas backup?",en:"What should be done after a backup?"},o:{ms:["Uji pemulihan","Padam backup","Format semua disk"],en:["Test recovery","Delete the backup","Format all disks"]},a:0},
{q:{ms:"Jika ruang destinasi tidak cukup?",en:"What if the destination lacks space?"},o:{ms:["Backup mungkin gagal","DNS menjadi cepat","User terbuka"],en:["The backup may fail","DNS becomes faster","The user unlocks"]},a:0},
{q:{ms:"Apakah tanda backup berjaya?",en:"What indicates a successful backup?"},o:{ms:["Status Completed successfully","Server padam","IP berubah"],en:["Completed successfully status","The server shuts down","The IP changes"]},a:0}
];

function card(icon,title,text){return `<article class="info-card"><span>${icon}</span><h3>${title}</h3><p>${text}</p></article>`}
function render(){const s=slides[step];app.innerHTML=`<div class="kp-shell"><header class="kp-header"><button onclick="goDashboard()">← Dashboard</button><div class="kp-progress"><i style="width:${((step+1)/slides.length)*100}%"></i></div><span>${step+1}/${slides.length}</span></header><section class="card kp-stage"><span class="kp-chip">KP10</span><div class="kp-hero-icon">${s.icon}</div><h1>${s.title[lang]}</h1><p class="kp-lead">${s.lead[lang]}</p>${s.lab?renderLab():s.activity?renderActivity():s.quiz?renderQuiz():s.body()}<div id="feedback" class="feedback"></div><div class="kp-nav"><button class="secondary" onclick="previous()" ${step===0?"disabled":""}>← ${lang==="ms"?"Sebelumnya":"Previous"}</button><button onclick="next()">${step===slides.length-1?(lang==="ms"?"SELESAIKAN SERVER HERO":"COMPLETE SERVER HERO"):(lang==="ms"?"Seterusnya":"Next")} →</button></div></section></div>`}
function renderLab(){const steps=["Install Feature","Backup Once","Backup Type","Destination","Run Backup","Open Recovery","Select Backup","Restore Folder","Verification"];return `<div class="lab-window"><div class="lab-titlebar"><b>Windows Server Backup</b><span>— □ ×</span></div><div class="lab-body"><aside class="lab-sidebar">${steps.map((x,i)=>`<button class="${i===labStep?"active":""}">${i+1}. ${x}</button>`).join("")}</aside><section class="lab-content"><h2>${steps[labStep]}</h2><div class="lab-panel">${labControls()}<div id="labStatus" class="lab-status">${lang==="ms"?"Langkah "+(labStep+1)+" daripada "+steps.length:"Step "+(labStep+1)+" of "+steps.length}</div></div></section></div></div>`}
function labControls(){switch(labStep){
case 0:return `<p>${lang==="ms"?"Pasang Windows Server Backup melalui Add Roles and Features.":"Install Windows Server Backup through Add Roles and Features."}</p><div class="lab-options"><button class="lab-option" onclick="advanceLab()">☑ Windows Server Backup → Install</button><button class="lab-option" onclick="labWrong()">☐ Print Services</button></div>`;
case 1:return `<p>${lang==="ms"?"Pilih Backup Once.":"Choose Backup Once."}</p><div class="lab-options"><button class="lab-option" onclick="advanceLab()">Backup Once</button><button class="lab-option" onclick="labWrong()">Recovery</button></div>`;
case 2:return `<p>${lang==="ms"?"Pilih Full Server.":"Choose Full Server."}</p><div class="lab-options"><button class="lab-option" onclick="advanceLab()">Full Server</button><button class="lab-option" onclick="labWrong()">Custom: No items selected</button></div>`;
case 3:return `<label>Backup Destination</label><input id="destInput" class="lab-input" placeholder="E:"><div class="lab-actions"><button onclick="checkDestination()">Next</button></div>`;
case 4:return `<p>${lang==="ms"?"Mulakan backup dan tunggu status Completed successfully.":"Start the backup and wait for Completed successfully."}</p><div class="lab-options"><button class="lab-option" onclick="advanceLab()">Start Backup</button></div>`;
case 5:return `<p>${lang==="ms"?"Buka Recovery Wizard.":"Open the Recovery Wizard."}</p><div class="lab-options"><button class="lab-option" onclick="advanceLab()">Recover</button></div>`;
case 6:return `<p>${lang==="ms"?"Pilih backup paling terkini.":"Select the most recent backup."}</p><div class="lab-options"><button class="lab-option" onclick="advanceLab()">Latest Backup</button></div>`;
case 7:return `<label>Folder to restore</label><input id="folderInput" class="lab-input" placeholder="D:\\DATA\\IMPORTANT"><div class="lab-actions"><button onclick="checkFolder()">Restore</button></div>`;
default:return `<p>${lang==="ms"?"Semak folder D:\\DATA\\IMPORTANT telah dipulihkan.":"Verify that D:\\DATA\\IMPORTANT has been restored."}</p><div class="lab-options"><button class="lab-option" onclick="finishLab()">Verify Recovery</button></div>`;
}}
function advanceLab(){labStep++;SHV5?.sound?.("correct");render()}
function labWrong(){SHV5?.sound?.("wrong");const e=document.getElementById("labStatus");if(e){e.textContent=lang==="ms"?"Pilihan salah. Cuba lagi.":"Incorrect option. Try again.";e.classList.add("error")}}
function checkDestination(){const v=document.getElementById("destInput").value.trim().toUpperCase();if(v==="E:"||v==="E"){lab.destination=true;labStep++;render()}else labWrong()}
function checkFolder(){const v=document.getElementById("folderInput").value.trim().toUpperCase().replaceAll("/","\\");if(v==="D:\\DATA\\IMPORTANT"){lab.recovery=true;labStep++;render()}else labWrong()}
function finishLab(){lab.tested=true;feedback(lang==="ms"?"Backup dan pemulihan berjaya! Folder penting telah dipulihkan.":"Backup and recovery complete! The important folder has been restored.","good");SHV5?.sound?.("complete")}
function renderActivity(){const shuffled=[...pairs.map((p,i)=>({i,text:p.r[lang]}))].sort(()=>Math.random()-.5);return `<div class="activity-board"><div class="activity-col">${pairs.map((p,i)=>`<button class="match-btn ${matched.has(i)?"matched":""}" data-left="${i}" onclick="pickLeft(${i},this)">${p.l[lang]}</button>`).join("")}</div><div class="activity-col">${shuffled.map(x=>`<button class="match-btn ${matched.has(x.i)?"matched":""}" data-right="${x.i}" onclick="pickRight(${x.i},this)">${x.text}</button>`).join("")}</div></div>`}
function pickLeft(i,b){if(matched.has(i))return;selectedLeft=i;document.querySelectorAll("[data-left]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}
function pickRight(i,b){if(selectedLeft===null)return;if(i===selectedLeft){matched.add(i);document.querySelector(`[data-left="${i}"]`)?.classList.add("matched");b.classList.add("matched");selectedLeft=null;feedback(lang==="ms"?"Padanan betul!":"Correct match!","good")}else feedback(lang==="ms"?"Belum tepat. Cuba lagi.":"Not correct yet. Try again.","bad")}
function renderQuiz(){return `<div class="quiz-list">${quiz.map((q,qi)=>`<article class="quiz-card"><h3>${qi+1}. ${q.q[lang]}</h3>${q.o[lang].map((o,oi)=>`<button class="quiz-option ${answers[qi]===oi?"selected":""}" onclick="answer(${qi},${oi},this)">${String.fromCharCode(65+oi)}. ${o}</button>`).join("")}</article>`).join("")}</div>`}
function answer(q,o,b){answers[q]=o;document.querySelectorAll(`.quiz-card:nth-child(${q+1}) .quiz-option`).forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}
function feedback(text,type){const e=document.getElementById("feedback");if(e){e.textContent=text;e.className="feedback "+type}}
function previous(){if(step>0){step--;render()}}
function next(){if(slides[step].lab&&!lab.tested){feedback(lang==="ms"?"Lengkapkan Virtual Lab dahulu.":"Complete the Virtual Lab first.","bad");return}if(slides[step].activity&&matched.size<pairs.length){feedback(lang==="ms"?"Lengkapkan semua padanan dahulu.":"Complete all matches first.","bad");return}if(slides[step].quiz){if(Object.keys(answers).length<quiz.length){feedback(lang==="ms"?"Jawab semua soalan dahulu.":"Answer all questions first.","bad");return}complete();return}if(step<slides.length-1){step++;render()}}
function complete(){let correct=0;quiz.forEach((q,i)=>{if(answers[i]===q.a)correct++});const score=Math.round(correct/quiz.length*100);state.completedKP=state.completedKP||[];const first=!state.completedKP.includes(10);if(first)state.completedKP.push(10);state.unlocked=10;state.badges=state.badges||[];if(first){state.xp=(state.xp||0)+350+(correct*15);state.coins=(state.coins||0)+250;if(!state.badges.includes("backup-specialist"))state.badges.push("backup-specialist");if(!state.badges.includes("server-hero-master"))state.badges.push("server-hero-master")}SHStorage.save(state);SHV5?.sound?.("complete");app.innerHTML=`<section class="center"><div class="card hero"><div class="complete-icon">👑</div><h1>${lang==="ms"?"SERVER HERO MASTER!":"SERVER HERO MASTER!"}</h1><div class="score-ring" style="--score:${score*3.6}deg"><b>${score}%</b></div><p>${lang==="ms"?"Tahniah! Anda telah menyelesaikan semua KP01 hingga KP10.":"Congratulations! You have completed KP01 through KP10."}</p><p><strong>${first?`+${350+(correct*15)} XP · +250 Coin · 2 Badge`:(lang==="ms"?"Ganjaran telah dituntut sebelum ini.":"Reward was claimed previously.")}</strong></p><div style="display:flex;gap:10px;justify-content:center;flex-wrap:wrap"><button class="primary" onclick="goDashboard()">Dashboard</button><button class="primary" onclick="SHV5.certificate(state)">🎓 ${lang==="ms"?"Sijil":"Certificate"}</button></div></div></section>`}
function goDashboard(){window.location.href="index.html"}
render();
