const app=document.getElementById("kpApp");
let state=SHStorage.load();
const lang=state.lang||"ms";
let step=0,labStep=0,selectedLeft=null;
const matched=new Set();
let answers={},lab={tested:false};

const slides=[
{icon:"📁",title:{ms:"Misi KP11: File Server dan Kebenaran Folder",en:"KP11 Mission: File Server and Folder Permissions"},lead:{ms:"Bina perkongsian folder yang selamat untuk jabatan HR.",en:"Build a secure shared folder for the HR department."},body:()=>`<div class="story-alert"><strong>🚨 Mission Briefing</strong>${lang==="ms"?"Jabatan HR memerlukan folder rangkaian yang hanya boleh diakses oleh HR-GROUP.":"The HR department needs a network folder accessible only to HR-GROUP."}</div><div class="card-grid three">${card("📂",lang==="ms"?"Objektif 1":"Objective 1",lang==="ms"?"Mencipta folder dan perkongsian rangkaian.":"Create folders and a network share.")}${card("🔐",lang==="ms"?"Objektif 2":"Objective 2",lang==="ms"?"Menetapkan Share dan NTFS Permission.":"Configure Share and NTFS permissions.")}${card("💻",lang==="ms"?"Objektif 3":"Objective 3",lang==="ms"?"Map drive dan menguji akses klien.":"Map a drive and test client access.")}</div>`},
{icon:"🗄️",title:{ms:"Konsep File Server",en:"File Server Concepts"},lead:{ms:"File Server menyimpan dan berkongsi fail secara berpusat.",en:"A File Server stores and shares files centrally."},body:()=>`<div class="card-grid three">${card("📚",lang==="ms"?"Penyimpanan Berpusat":"Central Storage",lang==="ms"?"Fail organisasi disimpan pada lokasi terkawal.":"Files are stored in a controlled location.")}${card("👥",lang==="ms"?"Akses Berkumpulan":"Group Access",lang==="ms"?"Kebenaran diberikan melalui kumpulan.":"Permissions are assigned through groups.")}${card("🛡️",lang==="ms"?"Keselamatan":"Security",lang==="ms"?"Share dan NTFS mengawal akses.":"Share and NTFS permissions control access.")}</div>`},
{icon:"🔑",title:{ms:"Jenis Kebenaran",en:"Permission Types"},lead:{ms:"Gabungan paling ketat antara Share dan NTFS akan digunakan.",en:"The most restrictive combination of Share and NTFS applies."},body:()=>`<table class="permission-table"><tr><th>Permission</th><th>${lang==="ms"?"Fungsi":"Function"}</th></tr><tr><td>Read</td><td>${lang==="ms"?"Lihat dan buka fail":"View and open files"}</td></tr><tr><td>Modify</td><td>${lang==="ms"?"Cipta, ubah dan padam fail":"Create, edit and delete files"}</td></tr><tr><td>Full Control</td><td>${lang==="ms"?"Semua akses termasuk ubah kebenaran":"All access including permission changes"}</td></tr></table>`},
{icon:"🖥️",title:{ms:"Virtual Lab: File Server",en:"Virtual Lab: File Server"},lead:{ms:"Cipta folder HR, tetapkan kebenaran dan map drive Z:.",en:"Create the HR folder, configure permissions and map drive Z:."},lab:true},
{icon:"🧯",title:{ms:"Penyelesaian Masalah",en:"Troubleshooting"},lead:{ms:"Semak laluan UNC, kumpulan dan kebenaran efektif.",en:"Check the UNC path, group membership and effective permissions."},body:()=>`<div class="card-grid two">${card("🌐","UNC Path","\\\\SERVERHERO\\\\HR")}${card("👥","HR-GROUP",lang==="ms"?"Pastikan pengguna menjadi ahli kumpulan.":"Ensure the user is a group member.")}${card("🔐",lang==="ms"?"Effective Access":"Effective Access",lang==="ms"?"Semak Share dan NTFS bersama-sama.":"Review Share and NTFS together.")}${card("🔄",lang==="ms"?"Login Semula":"Sign In Again",lang==="ms"?"Log masuk semula selepas perubahan kumpulan.":"Sign in again after group changes.")}</div>`},
{icon:"🎮",title:{ms:"Aktiviti Padanan",en:"Matching Activity"},lead:{ms:"Padankan kebenaran dengan fungsinya.",en:"Match permissions with their functions."},activity:true},
{icon:"🧠",title:{ms:"Kuiz KP11",en:"KP11 Quiz"},lead:{ms:"Jawab semua 10 soalan.",en:"Answer all 10 questions."},quiz:true}
];

const pairs=[
{l:{ms:"Read",en:"Read"},r:{ms:"Lihat dan buka fail",en:"View and open files"}},
{l:{ms:"Modify",en:"Modify"},r:{ms:"Cipta, ubah dan padam fail",en:"Create, edit and delete files"}},
{l:{ms:"Full Control",en:"Full Control"},r:{ms:"Semua akses termasuk ubah kebenaran",en:"All access including permission changes"}},
{l:{ms:"UNC Path",en:"UNC Path"},r:{ms:"Laluan perkongsian rangkaian",en:"Network share path"}}
];

const quiz=[
{q:{ms:"Fungsi File Server?",en:"Function of a File Server?"},o:{ms:["Simpan dan kongsi fail","Beri IP","Resolusi DNS"],en:["Store and share files","Assign IPs","Resolve DNS"]},a:0},
{q:{ms:"Contoh UNC Path?",en:"Example of a UNC path?"},o:{ms:["\\\\SERVERHERO\\HR","D:\\HR","192.168.10.1"],en:["\\\\SERVERHERO\\HR","D:\\HR","192.168.10.1"]},a:0},
{q:{ms:"Read membenarkan?",en:"Read allows?"},o:{ms:["Lihat dan buka fail","Ubah semua kebenaran","Format server"],en:["View and open files","Change all permissions","Format server"]},a:0},
{q:{ms:"Modify membenarkan?",en:"Modify allows?"},o:{ms:["Cipta, ubah dan padam","Lihat sahaja","Tukar domain"],en:["Create, edit and delete","View only","Change domain"]},a:0},
{q:{ms:"Full Control termasuk?",en:"Full Control includes?"},o:{ms:["Ubah kebenaran","Read sahaja","Ping sahaja"],en:["Change permissions","Read only","Ping only"]},a:0},
{q:{ms:"Share dan NTFS berbeza, yang dipakai?",en:"If Share and NTFS differ, which applies?"},o:{ms:["Gabungan paling ketat","Paling longgar","Share sahaja"],en:["Most restrictive combination","Least restrictive","Share only"]},a:0},
{q:{ms:"Nama kumpulan HR?",en:"HR group name?"},o:{ms:["HR-GROUP","IT-STAFF","ALL-USERS"],en:["HR-GROUP","IT-STAFF","ALL-USERS"]},a:0},
{q:{ms:"Drive letter dalam lab?",en:"Drive letter in the lab?"},o:{ms:["Z:","C:","A:"],en:["Z:","C:","A:"]},a:0},
{q:{ms:"Deny digunakan?",en:"Deny should be used?"},o:{ms:["Dengan berhati-hati","Pada semua pengguna","Untuk tambah akses"],en:["Carefully","For all users","To increase access"]},a:0},
{q:{ms:"Selepas ubah group membership?",en:"After changing group membership?"},o:{ms:["Log masuk semula","Format disk","Padam DNS"],en:["Sign in again","Format disk","Delete DNS"]},a:0}
];

function card(icon,title,text){return `<article class="info-card"><span>${icon}</span><h3>${title}</h3><p>${text}</p></article>`}
function render(){const s=slides[step];app.innerHTML=`<div class="kp-shell"><header class="kp-header"><button onclick="goDashboard()">← Dashboard</button><div class="kp-progress"><i style="width:${((step+1)/slides.length)*100}%"></i></div><span>${step+1}/${slides.length}</span></header><section class="card kp-stage"><span class="kp-chip">KP11</span><div class="kp-hero-icon">${s.icon}</div><h1>${s.title[lang]}</h1><p class="kp-lead">${s.lead[lang]}</p>${s.lab?renderLab():s.activity?renderActivity():s.quiz?renderQuiz():s.body()}<div id="feedback" class="feedback"></div><div class="kp-nav"><button class="secondary" onclick="previous()" ${step===0?"disabled":""}>← ${lang==="ms"?"Sebelumnya":"Previous"}</button><button onclick="next()">${step===slides.length-1?(lang==="ms"?"SELESAIKAN KP":"COMPLETE KP"):(lang==="ms"?"Seterusnya":"Next")} →</button></div></section></div>`}
function renderLab(){const steps=["Install File Server","Create Folders","Advanced Sharing","Share Permission","NTFS Permission","Map Drive","Client Test"];return `<div class="lab-window"><div class="lab-titlebar"><b>File and Storage Services</b><span>— □ ×</span></div><div class="lab-body"><aside class="lab-sidebar">${steps.map((x,i)=>`<button class="${i===labStep?"active":""}">${i+1}. ${x}</button>`).join("")}</aside><section class="lab-content"><h2>${steps[labStep]}</h2><div class="lab-panel">${labControls()}<div id="labStatus" class="lab-status">${lang==="ms"?"Langkah "+(labStep+1)+" daripada "+steps.length:"Step "+(labStep+1)+" of "+steps.length}</div></div></section></div></div>`}
function labControls(){switch(labStep){
case 0:return `<div class="lab-options"><button class="lab-option" onclick="advanceLab()">☑ File and Storage Services → File Server</button><button class="lab-option" onclick="labWrong()">☐ DHCP Server</button></div>`;
case 1:return `<label>Root Folder</label><input id="rootInput" class="lab-input" placeholder="D:\\SHARE"><label>Department Folder</label><input id="deptInput" class="lab-input" placeholder="HR"><div class="lab-actions"><button onclick="checkFolders()">Create Folders</button></div>`;
case 2:return `<div class="lab-options"><button class="lab-option" onclick="advanceLab()">☑ Share this folder · Share name: HR</button><button class="lab-option" onclick="labWrong()">Hide this folder</button></div>`;
case 3:return `<div class="lab-options"><button class="lab-option" onclick="advanceLab()">HR-GROUP · Allow Change + Read</button><button class="lab-option" onclick="labWrong()">Everyone · Full Control</button></div>`;
case 4:return `<div class="lab-options"><button class="lab-option" onclick="advanceLab()">HR-GROUP · Allow Modify</button><button class="lab-option" onclick="labWrong()">HR-GROUP · Deny All</button></div>`;
case 5:return `<label>UNC Path</label><input id="uncInput" class="lab-input" placeholder="\\\\SERVERHERO\\HR"><label>Drive Letter</label><input id="driveInput" class="lab-input" placeholder="Z:"><div class="lab-actions"><button onclick="checkMap()">Map Drive</button></div>`;
default:return `<div class="lab-options"><button class="lab-option" onclick="finishLab()">Create test-document.txt</button></div>`;
}}
function advanceLab(){labStep++;SHV5?.sound?.("correct");render()}
function labWrong(){SHV5?.sound?.("wrong");const e=document.getElementById("labStatus");if(e){e.textContent=lang==="ms"?"Pilihan salah. Cuba lagi.":"Incorrect option. Try again.";e.classList.add("error")}}
function checkFolders(){const r=document.getElementById("rootInput").value.trim().toUpperCase().replaceAll("/","\\"),d=document.getElementById("deptInput").value.trim().toUpperCase();if(r==="D:\\SHARE"&&d==="HR"){labStep++;render()}else labWrong()}
function checkMap(){const u=document.getElementById("uncInput").value.trim().toUpperCase().replaceAll("/","\\"),d=document.getElementById("driveInput").value.trim().toUpperCase();if(u==="\\\\SERVERHERO\\HR"&&(d==="Z:"||d==="Z")){labStep++;render()}else labWrong()}
function finishLab(){lab.tested=true;feedback(lang==="ms"?"File Server berjaya! HR-GROUP boleh mengakses drive Z:.":"File Server complete! HR-GROUP can access drive Z:.","good");SHV5?.sound?.("complete")}
function renderActivity(){const shuffled=[...pairs.map((p,i)=>({i,text:p.r[lang]}))].sort(()=>Math.random()-.5);return `<div class="activity-board"><div class="activity-col">${pairs.map((p,i)=>`<button class="match-btn ${matched.has(i)?"matched":""}" data-left="${i}" onclick="pickLeft(${i},this)">${p.l[lang]}</button>`).join("")}</div><div class="activity-col">${shuffled.map(x=>`<button class="match-btn ${matched.has(x.i)?"matched":""}" data-right="${x.i}" onclick="pickRight(${x.i},this)">${x.text}</button>`).join("")}</div></div>`}
function pickLeft(i,b){if(matched.has(i))return;selectedLeft=i;document.querySelectorAll("[data-left]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}
function pickRight(i,b){if(selectedLeft===null)return;if(i===selectedLeft){matched.add(i);document.querySelector(`[data-left="${i}"]`)?.classList.add("matched");b.classList.add("matched");selectedLeft=null;feedback(lang==="ms"?"Padanan betul!":"Correct match!","good")}else feedback(lang==="ms"?"Belum tepat. Cuba lagi.":"Not correct yet. Try again.","bad")}
function renderQuiz(){return `<div class="quiz-list">${quiz.map((q,qi)=>`<article class="quiz-card"><h3>${qi+1}. ${q.q[lang]}</h3>${q.o[lang].map((o,oi)=>`<button class="quiz-option ${answers[qi]===oi?"selected":""}" onclick="answer(${qi},${oi},this)">${String.fromCharCode(65+oi)}. ${o}</button>`).join("")}</article>`).join("")}</div>`}
function answer(q,o,b){answers[q]=o;document.querySelectorAll(`.quiz-card:nth-child(${q+1}) .quiz-option`).forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}
function feedback(text,type){const e=document.getElementById("feedback");if(e){e.textContent=text;e.className="feedback "+type}}
function previous(){if(step>0){step--;render()}}
function next(){if(slides[step].lab&&!lab.tested){feedback(lang==="ms"?"Lengkapkan Virtual Lab dahulu.":"Complete the Virtual Lab first.","bad");return}if(slides[step].activity&&matched.size<pairs.length){feedback(lang==="ms"?"Lengkapkan semua padanan dahulu.":"Complete all matches first.","bad");return}if(slides[step].quiz){if(Object.keys(answers).length<quiz.length){feedback(lang==="ms"?"Jawab semua soalan dahulu.":"Answer all questions first.","bad");return}complete();return}if(step<slides.length-1){step++;render()}}
function complete(){let correct=0;quiz.forEach((q,i)=>{if(answers[i]===q.a)correct++});const score=Math.round(correct/quiz.length*100);state.completedKP=state.completedKP||[];const first=!state.completedKP.includes(11);if(first)state.completedKP.push(11);state.unlocked=Math.max(state.unlocked||11,12);state.badges=state.badges||[];if(first){state.xp=(state.xp||0)+350+(correct*15);state.coins=(state.coins||0)+250;if(!state.badges.includes("file-server-specialist"))state.badges.push("file-server-specialist")}SHStorage.save(state);SHV5?.sound?.("complete");app.innerHTML=`<section class="center"><div class="card hero"><div class="complete-icon">📁</div><h1>File Server Specialist!</h1><div class="score-ring" style="--score:${score*3.6}deg"><b>${score}%</b></div><p>${lang==="ms"?"KP11 selesai dan KP12 telah dibuka.":"KP11 is complete and KP12 has been unlocked."}</p><p><strong>${first?`+${350+(correct*15)} XP · +250 Coin · Badge File Server Specialist`:(lang==="ms"?"Ganjaran telah dituntut sebelum ini.":"Reward was claimed previously.")}</strong></p><button class="primary" onclick="goDashboard()">Dashboard</button></div></section>`}
function goDashboard(){window.location.href="index.html"}
render();
