const app=document.getElementById("kpApp");
let state=SHStorage.load();
const lang=state.lang||"ms";
let step=0,labStep=0,selectedLeft=null;
const matched=new Set();
let answers={},lab={tested:false};

const slides=[
{icon:"📜",title:{ms:"Misi KP12: Group Policy Object",en:"KP12 Mission: Group Policy Object"},lead:{ms:"Cipta dan laksanakan polisi berpusat kepada pengguna dalam OU STAFF.",en:"Create and apply central policies to users in the STAFF OU."},body:()=>`<div class="story-alert"><strong>🚨 Mission Briefing</strong>${lang==="ms"?"Pengguna STAFF perlu menerima konfigurasi keselamatan yang sama. Anda perlu mencipta GPO, link kepada OU STAFF dan menguji polisi pada klien.":"STAFF users need the same security configuration. You must create a GPO, link it to the STAFF OU and test the policy on a client."}</div><div class="card-grid three">${card("🧭",lang==="ms"?"Objektif 1":"Objective 1",lang==="ms"?"Memahami fungsi dan struktur GPO.":"Understand GPO functions and structure.")}${card("⚙️",lang==="ms"?"Objektif 2":"Objective 2",lang==="ms"?"Mencipta dan mengedit STAFF-POLICY.":"Create and edit STAFF-POLICY.")}${card("🧪",lang==="ms"?"Objektif 3":"Objective 3",lang==="ms"?"Menguji polisi dengan gpupdate /force.":"Test the policy with gpupdate /force.")}</div>`},
{icon:"🧠",title:{ms:"Apakah Itu GPO?",en:"What Is a GPO?"},lead:{ms:"GPO membolehkan pentadbir mengawal konfigurasi pengguna dan komputer secara berpusat.",en:"A GPO allows administrators to centrally control user and computer settings."},body:()=>`<div class="card-grid three">${card("👤",lang==="ms"?"User Configuration":"User Configuration",lang==="ms"?"Polisi yang digunakan pada akaun pengguna.":"Policies applied to user accounts.")}${card("💻",lang==="ms"?"Computer Configuration":"Computer Configuration",lang==="ms"?"Polisi yang digunakan pada komputer.":"Policies applied to computers.")}${card("🔗",lang==="ms"?"Link GPO":"Link GPO",lang==="ms"?"GPO perlu di-link kepada Site, Domain atau OU.":"A GPO must be linked to a Site, Domain or OU.")}</div>`},
{icon:"🗂️",title:{ms:"Struktur Pelaksanaan GPO",en:"GPO Processing Structure"},lead:{ms:"Polisi diproses mengikut Local, Site, Domain dan OU.",en:"Policies are processed in Local, Site, Domain and OU order."},body:()=>`<div class="gpo-tree"><div class="gpo-node"><strong>1. Local Policy</strong></div><div class="gpo-node"><strong>2. Site</strong></div><div class="gpo-node"><strong>3. Domain</strong></div><div class="gpo-node"><strong>4. OU STAFF</strong><div class="policy-path">STAFF-POLICY</div></div></div>`},
{icon:"🖥️",title:{ms:"Virtual Lab: Group Policy Management",en:"Virtual Lab: Group Policy Management"},lead:{ms:"Cipta STAFF-POLICY, link kepada OU STAFF dan uji pada klien.",en:"Create STAFF-POLICY, link it to the STAFF OU and test it on a client."},lab:true},
{icon:"🧯",title:{ms:"Penyelesaian Masalah GPO",en:"GPO Troubleshooting"},lead:{ms:"Semak link, skop, penapisan dan keputusan polisi.",en:"Check the link, scope, filtering and policy results."},body:()=>`<div class="card-grid two">${card("🔗",lang==="ms"?"GPO Link":"GPO Link",lang==="ms"?"Pastikan GPO di-link kepada OU yang betul.":"Ensure the GPO is linked to the correct OU.")}${card("👥",lang==="ms"?"Security Filtering":"Security Filtering",lang==="ms"?"Semak pengguna atau kumpulan mempunyai Apply Group Policy.":"Check that the user or group has Apply Group Policy.")}${card("🔄","gpupdate /force",lang==="ms"?"Paksa klien memproses semula polisi.":"Force the client to process policies again.")}${card("📊","gpresult /r",lang==="ms"?"Papar GPO yang berjaya digunakan.":"Display the GPOs that were applied.")}</div>`},
{icon:"🎮",title:{ms:"Aktiviti Padanan GPO",en:"GPO Matching Activity"},lead:{ms:"Padankan istilah GPO dengan fungsinya.",en:"Match each GPO term with its function."},activity:true},
{icon:"🧠",title:{ms:"Kuiz KP12",en:"KP12 Quiz"},lead:{ms:"Jawab semua 10 soalan untuk menamatkan KP12.",en:"Answer all 10 questions to complete KP12."},quiz:true}
];

const pairs=[
{l:{ms:"User Configuration",en:"User Configuration"},r:{ms:"Polisi untuk akaun pengguna",en:"Policies for user accounts"}},
{l:{ms:"Computer Configuration",en:"Computer Configuration"},r:{ms:"Polisi untuk komputer",en:"Policies for computers"}},
{l:{ms:"gpupdate /force",en:"gpupdate /force"},r:{ms:"Memproses semula polisi",en:"Reprocess policies"}},
{l:{ms:"gpresult /r",en:"gpresult /r"},r:{ms:"Memaparkan keputusan polisi",en:"Displays policy results"}}
];

const quiz=[
{q:{ms:"Apakah fungsi utama GPO?",en:"What is the main function of a GPO?"},o:{ms:["Mengawal konfigurasi secara berpusat","Memberi IP","Menyimpan backup"],en:["Centrally control configurations","Assign IP addresses","Store backups"]},a:0},
{q:{ms:"GPO boleh di-link kepada?",en:"A GPO can be linked to?"},o:{ms:["Site, Domain atau OU","RAM","BIOS sahaja"],en:["Site, Domain or OU","RAM","BIOS only"]},a:0},
{q:{ms:"Polisi pengguna berada di?",en:"Where are user policies located?"},o:{ms:["User Configuration","Computer Configuration sahaja","DNS Manager"],en:["User Configuration","Computer Configuration only","DNS Manager"]},a:0},
{q:{ms:"Polisi komputer berada di?",en:"Where are computer policies located?"},o:{ms:["Computer Configuration","User Configuration sahaja","DHCP Manager"],en:["Computer Configuration","User Configuration only","DHCP Manager"]},a:0},
{q:{ms:"Nama GPO dalam lab?",en:"What is the GPO name in the lab?"},o:{ms:["STAFF-POLICY","DEFAULT-ONLY","SERVER-GROUP"],en:["STAFF-POLICY","DEFAULT-ONLY","SERVER-GROUP"]},a:0},
{q:{ms:"GPO di-link kepada OU?",en:"Which OU is the GPO linked to?"},o:{ms:["STAFF","HR","COMPUTERS"],en:["STAFF","HR","COMPUTERS"]},a:0},
{q:{ms:"Arahan paksa kemas kini polisi?",en:"Which command forces policy update?"},o:{ms:["gpupdate /force","ipconfig /renew","nslookup"],en:["gpupdate /force","ipconfig /renew","nslookup"]},a:0},
{q:{ms:"Arahan semak keputusan GPO?",en:"Which command checks GPO results?"},o:{ms:["gpresult /r","format","diskpart"],en:["gpresult /r","format","diskpart"]},a:0},
{q:{ms:"Security Filtering digunakan untuk?",en:"What is Security Filtering used for?"},o:{ms:["Hadkan siapa menerima GPO","Tetapkan IP","Buat backup"],en:["Limit who receives the GPO","Set an IP","Create a backup"]},a:0},
{q:{ms:"Jika GPO tidak berfungsi, semak dahulu?",en:"If a GPO does not work, check first?"},o:{ms:["Link dan skop","Warna desktop sahaja","Nama folder"],en:["Link and scope","Only desktop colour","Folder name"]},a:0}
];

function card(icon,title,text){return `<article class="info-card"><span>${icon}</span><h3>${title}</h3><p>${text}</p></article>`}
function render(){const s=slides[step];app.innerHTML=`<div class="kp-shell"><header class="kp-header"><button onclick="goDashboard()">← Dashboard</button><div class="kp-progress"><i style="width:${((step+1)/slides.length)*100}%"></i></div><span>${step+1}/${slides.length}</span></header><section class="card kp-stage"><span class="kp-chip">KP12</span><div class="kp-hero-icon">${s.icon}</div><h1>${s.title[lang]}</h1><p class="kp-lead">${s.lead[lang]}</p>${s.lab?renderLab():s.activity?renderActivity():s.quiz?renderQuiz():s.body()}<div id="feedback" class="feedback"></div><div class="kp-nav"><button class="secondary" onclick="previous()" ${step===0?"disabled":""}>← ${lang==="ms"?"Sebelumnya":"Previous"}</button><button onclick="next()">${step===slides.length-1?(lang==="ms"?"SELESAIKAN KP":"COMPLETE KP"):(lang==="ms"?"Seterusnya":"Next")} →</button></div></section></div>`}
function renderLab(){const steps=["Open GPMC","Create GPO","Link to OU","Disable Control Panel","Set Wallpaper","Password Policy","Update Client","Verify Result"];return `<div class="lab-window"><div class="lab-titlebar"><b>Group Policy Management</b><span>— □ ×</span></div><div class="lab-body"><aside class="lab-sidebar">${steps.map((x,i)=>`<button class="${i===labStep?"active":""}">${i+1}. ${x}</button>`).join("")}</aside><section class="lab-content"><h2>${steps[labStep]}</h2><div class="lab-panel">${labControls()}<div id="labStatus" class="lab-status">${lang==="ms"?"Langkah "+(labStep+1)+" daripada "+steps.length:"Step "+(labStep+1)+" of "+steps.length}</div></div></section></div></div>`}
function labControls(){switch(labStep){
case 0:return `<div class="lab-options"><button class="lab-option" onclick="advanceLab()">Tools → Group Policy Management</button><button class="lab-option" onclick="labWrong()">Tools → DNS</button></div>`;
case 1:return `<label>GPO Name</label><input id="gpoInput" class="lab-input" placeholder="STAFF-POLICY"><div class="lab-actions"><button onclick="checkGPO()">Create</button></div>`;
case 2:return `<div class="lab-options"><button class="lab-option" onclick="advanceLab()">Link STAFF-POLICY to OU STAFF</button><button class="lab-option" onclick="labWrong()">Link to Computers container</button></div>`;
case 3:return `<div class="lab-options"><button class="lab-option" onclick="advanceLab()">User Configuration → Administrative Templates → Control Panel → Prohibit access = Enabled</button><button class="lab-option" onclick="labWrong()">Not Configured</button></div>`;
case 4:return `<label>Wallpaper Path</label><input id="wallInput" class="lab-input" placeholder="\\\\SERVERHERO\\NETLOGON\\wallpaper.jpg"><div class="lab-actions"><button onclick="checkWallpaper()">Apply</button></div>`;
case 5:return `<div class="lab-options"><button class="lab-option" onclick="advanceLab()">Minimum password length = 8</button><button class="lab-option" onclick="labWrong()">Minimum password length = 0</button></div>`;
case 6:return `<div class="lab-options"><button class="lab-option" onclick="advanceLab()">Run gpupdate /force</button><button class="lab-option" onclick="labWrong()">Run ipconfig /release</button></div>`;
default:return `<div class="lab-options"><button class="lab-option" onclick="finishLab()">Run gpresult /r and verify STAFF-POLICY</button></div>`;
}}
function advanceLab(){labStep++;SHV5?.sound?.("correct");render()}
function labWrong(){SHV5?.sound?.("wrong");const e=document.getElementById("labStatus");if(e){e.textContent=lang==="ms"?"Pilihan salah. Cuba lagi.":"Incorrect option. Try again.";e.classList.add("error")}}
function checkGPO(){const v=document.getElementById("gpoInput").value.trim().toUpperCase();if(v==="STAFF-POLICY"){labStep++;render()}else labWrong()}
function checkWallpaper(){const v=document.getElementById("wallInput").value.trim().toUpperCase().replaceAll("/","\\");if(v==="\\\\SERVERHERO\\NETLOGON\\WALLPAPER.JPG"){labStep++;render()}else labWrong()}
function finishLab(){lab.tested=true;feedback(lang==="ms"?"GPO berjaya! STAFF-POLICY telah digunakan pada OU STAFF.":"GPO complete! STAFF-POLICY has been applied to the STAFF OU.","good");SHV5?.sound?.("complete")}
function renderActivity(){const shuffled=[...pairs.map((p,i)=>({i,text:p.r[lang]}))].sort(()=>Math.random()-.5);return `<div class="activity-board"><div class="activity-col">${pairs.map((p,i)=>`<button class="match-btn ${matched.has(i)?"matched":""}" data-left="${i}" onclick="pickLeft(${i},this)">${p.l[lang]}</button>`).join("")}</div><div class="activity-col">${shuffled.map(x=>`<button class="match-btn ${matched.has(x.i)?"matched":""}" data-right="${x.i}" onclick="pickRight(${x.i},this)">${x.text}</button>`).join("")}</div></div>`}
function pickLeft(i,b){if(matched.has(i))return;selectedLeft=i;document.querySelectorAll("[data-left]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}
function pickRight(i,b){if(selectedLeft===null)return;if(i===selectedLeft){matched.add(i);document.querySelector(`[data-left="${i}"]`)?.classList.add("matched");b.classList.add("matched");selectedLeft=null;feedback(lang==="ms"?"Padanan betul!":"Correct match!","good")}else feedback(lang==="ms"?"Belum tepat. Cuba lagi.":"Not correct yet. Try again.","bad")}
function renderQuiz(){return `<div class="quiz-list">${quiz.map((q,qi)=>`<article class="quiz-card"><h3>${qi+1}. ${q.q[lang]}</h3>${q.o[lang].map((o,oi)=>`<button class="quiz-option ${answers[qi]===oi?"selected":""}" onclick="answer(${qi},${oi},this)">${String.fromCharCode(65+oi)}. ${o}</button>`).join("")}</article>`).join("")}</div>`}
function answer(q,o,b){answers[q]=o;document.querySelectorAll(`.quiz-card:nth-child(${q+1}) .quiz-option`).forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}
function feedback(text,type){const e=document.getElementById("feedback");if(e){e.textContent=text;e.className="feedback "+type}}
function previous(){if(step>0){step--;render()}}
function next(){if(slides[step].lab&&!lab.tested){feedback(lang==="ms"?"Lengkapkan Virtual Lab dahulu.":"Complete the Virtual Lab first.","bad");return}if(slides[step].activity&&matched.size<pairs.length){feedback(lang==="ms"?"Lengkapkan semua padanan dahulu.":"Complete all matches first.","bad");return}if(slides[step].quiz){if(Object.keys(answers).length<quiz.length){feedback(lang==="ms"?"Jawab semua soalan dahulu.":"Answer all questions first.","bad");return}complete();return}if(step<slides.length-1){step++;render()}}
function complete(){let correct=0;quiz.forEach((q,i)=>{if(answers[i]===q.a)correct++});const score=Math.round(correct/quiz.length*100);state.completedKP=state.completedKP||[];const first=!state.completedKP.includes(12);if(first)state.completedKP.push(12);state.unlocked=Math.max(state.unlocked||12,13);state.badges=state.badges||[];if(first){state.xp=(state.xp||0)+380+(correct*15);state.coins=(state.coins||0)+280;if(!state.badges.includes("gpo-specialist"))state.badges.push("gpo-specialist")}SHStorage.save(state);SHV5?.sound?.("complete");app.innerHTML=`<section class="center"><div class="card hero"><div class="complete-icon">📜</div><h1>Group Policy Specialist!</h1><div class="score-ring" style="--score:${score*3.6}deg"><b>${score}%</b></div><p>${lang==="ms"?"KP12 selesai dan KP13 telah dibuka.":"KP12 is complete and KP13 has been unlocked."}</p><p><strong>${first?`+${380+(correct*15)} XP · +280 Coin · Badge GPO Specialist`:(lang==="ms"?"Ganjaran telah dituntut sebelum ini.":"Reward was claimed previously.")}</strong></p><button class="primary" onclick="goDashboard()">Dashboard</button></div></section>`}
function goDashboard(){window.location.href="index.html"}
render();
