const app=document.getElementById("kpApp");let state=SHStorage.load();const lang=state.lang||"ms";let step=0,labStep=0,selectedLeft=null;const matched=new Set();let answers={},lab={tested:false};
const slides=[
{icon:"👑",title:{ms:"KP13: Cabaran Akhir Enterprise",en:"KP13: Final Enterprise Challenge"},lead:{ms:"Gabungkan semua kemahiran KP01 hingga KP12.",en:"Combine all skills from KP01 to KP12."},body:()=>`<div class="story-alert"><strong>🚨 Final Mission</strong>${lang==="ms"?"Sediakan infrastruktur lengkap: AD DS, DNS, DHCP, pengguna, File Server, GPO dan backup.":"Prepare a complete infrastructure: AD DS, DNS, DHCP, users, File Server, GPO and backup."}</div><div class="card-grid three">${card("🛠️",lang==="ms"?"Integrasi":"Integration",lang==="ms"?"Gabungkan semua kemahiran.":"Combine all skills.")}${card("🧪",lang==="ms"?"Ujian":"Testing",lang==="ms"?"Sahkan setiap perkhidmatan.":"Verify every service.")}${card("🏆",lang==="ms"?"Penamat":"Completion",lang==="ms"?"Tamatkan SERVER HERO.":"Complete SERVER HERO.")}</div>`},
{icon:"🗺️",title:{ms:"Pelan Infrastruktur",en:"Infrastructure Plan"},lead:{ms:"Semak komponen enterprise.",en:"Review enterprise components."},body:()=>`<div class="challenge-grid">${challenge("🏢","AD DS","serverhero.local")}${challenge("🌐","DNS","dc01.serverhero.local")}${challenge("📡","DHCP","192.168.10.100–200")}${challenge("👥","Users & Groups","OU STAFF · IT-STAFF")}${challenge("📁","File Server","\\\\SERVERHERO\\HR")}${challenge("📜","GPO","STAFF-POLICY")}${challenge("💾","Backup","Drive E:")}${challenge("🧪","Client Test","nslookup · renew · gpresult")}</div>`},
{icon:"🖥️",title:{ms:"Virtual Lab: Enterprise Build",en:"Virtual Lab: Enterprise Build"},lead:{ms:"Lengkapkan semua tugas mengikut urutan.",en:"Complete all tasks in order."},lab:true},
{icon:"🎮",title:{ms:"Aktiviti Padanan",en:"Matching Activity"},lead:{ms:"Padankan perkhidmatan dengan fungsi.",en:"Match services with functions."},activity:true},
{icon:"🧠",title:{ms:"Penilaian Akhir",en:"Final Assessment"},lead:{ms:"Jawab 13 soalan akhir.",en:"Answer 13 final questions."},quiz:true}
];
const tasks=["Static IP","AD DS","DNS Zone","DHCP Scope","OU and User","Security Group","File Share","GPO","Backup","Client Test"];
const pairs=[{l:{ms:"AD DS",en:"AD DS"},r:{ms:"Pengurusan identiti",en:"Identity management"}},{l:{ms:"DNS",en:"DNS"},r:{ms:"Resolusi nama",en:"Name resolution"}},{l:{ms:"DHCP",en:"DHCP"},r:{ms:"IP automatik",en:"Automatic IP assignment"}},{l:{ms:"GPO",en:"GPO"},r:{ms:"Polisi berpusat",en:"Central policy"}}];
const quiz=[
{q:{ms:"IP server utama?",en:"Main server IP?"},o:{ms:["192.168.10.10","192.168.10.100","192.168.1.1"],en:["192.168.10.10","192.168.10.100","192.168.1.1"]},a:0},
{q:{ms:"Domain utama?",en:"Main domain?"},o:{ms:["serverhero.local","server.local","hero.com"],en:["serverhero.local","server.local","hero.com"]},a:0},
{q:{ms:"Peranan AD DS?",en:"Role of AD DS?"},o:{ms:["Urus identiti domain","Beri IP","Backup"],en:["Manage domain identities","Assign IPs","Backup"]},a:0},
{q:{ms:"DNS digunakan untuk?",en:"DNS is used for?"},o:{ms:["Resolusi nama","Simpan user","Map drive"],en:["Name resolution","Store users","Map drives"]},a:0},
{q:{ms:"DHCP digunakan untuk?",en:"DHCP is used for?"},o:{ms:["Beri IP automatik","Buat GPO","Reset password"],en:["Assign IPs automatically","Create GPOs","Reset passwords"]},a:0},
{q:{ms:"OU STAFF digunakan untuk?",en:"STAFF OU is used for?"},o:{ms:["Susun pengguna dan link GPO","Simpan backup","Buat DNS zone"],en:["Organise users and link GPOs","Store backups","Create DNS zones"]},a:0},
{q:{ms:"Share HR diakses melalui?",en:"HR share path?"},o:{ms:["\\\\SERVERHERO\\HR","D:\\HR","http://HR"],en:["\\\\SERVERHERO\\HR","D:\\HR","http://HR"]},a:0},
{q:{ms:"GPO digunakan?",en:"GPO used?"},o:{ms:["STAFF-POLICY","DEFAULT-ONLY","SERVER-GPO"],en:["STAFF-POLICY","DEFAULT-ONLY","SERVER-GPO"]},a:0},
{q:{ms:"Arahan paksa GPO?",en:"Force GPO update?"},o:{ms:["gpupdate /force","ipconfig /renew","nslookup"],en:["gpupdate /force","ipconfig /renew","nslookup"]},a:0},
{q:{ms:"Destinasi backup?",en:"Backup destination?"},o:{ms:["E:","C:","Z:"],en:["E:","C:","Z:"]},a:0},
{q:{ms:"Ujian DNS?",en:"DNS test?"},o:{ms:["nslookup","format","diskpart"],en:["nslookup","format","diskpart"]},a:0},
{q:{ms:"Ujian DHCP?",en:"DHCP test?"},o:{ms:["ipconfig /renew","gpresult /r","ping localhost"],en:["ipconfig /renew","gpresult /r","ping localhost"]},a:0},
{q:{ms:"Strategi backup?",en:"Backup strategy?"},o:{ms:["3-2-1","1-1-1","0-0-1"],en:["3-2-1","1-1-1","0-0-1"]},a:0}
];
function card(i,t,x){return `<article class="info-card"><span>${i}</span><h3>${t}</h3><p>${x}</p></article>`}function challenge(i,t,x){return `<article class="challenge-card"><span>${i}</span><h3>${t}</h3><p>${x}</p></article>`}
function render(){const s=slides[step];app.innerHTML=`<div class="kp-shell"><header class="kp-header"><button onclick="goDashboard()">← Dashboard</button><div class="kp-progress"><i style="width:${((step+1)/slides.length)*100}%"></i></div><span>${step+1}/${slides.length}</span></header><section class="card kp-stage"><span class="kp-chip">KP13</span><div class="kp-hero-icon">${s.icon}</div><h1>${s.title[lang]}</h1><p class="kp-lead">${s.lead[lang]}</p>${s.lab?renderLab():s.activity?renderActivity():s.quiz?renderQuiz():s.body()}<div id="feedback" class="feedback"></div><div class="kp-nav"><button class="secondary" onclick="previous()" ${step===0?"disabled":""}>← ${lang==="ms"?"Sebelumnya":"Previous"}</button><button onclick="next()">${step===slides.length-1?(lang==="ms"?"TAMATKAN SERVER HERO":"COMPLETE SERVER HERO"):(lang==="ms"?"Seterusnya":"Next")} →</button></div></section></div>`}
function renderLab(){return `<div class="lab-window"><div class="lab-titlebar"><b>Enterprise Deployment</b><span>— □ ×</span></div><div class="lab-body"><aside class="lab-sidebar">${tasks.map((x,i)=>`<button class="${i===labStep?"active":""}">${i+1}. ${x}</button>`).join("")}</aside><section class="lab-content"><h2>${tasks[labStep]}</h2><div class="lab-panel"><div class="lab-options"><button class="lab-option" onclick="advanceLab()">${lang==="ms"?"Laksanakan konfigurasi yang betul":"Apply the correct configuration"}</button><button class="lab-option" onclick="labWrong()">${lang==="ms"?"Pilihan salah":"Incorrect option"}</button></div><div id="labStatus" class="lab-status">${labStep+1}/${tasks.length}</div></div></section></div></div>`}
function advanceLab(){if(labStep<tasks.length-1){labStep++;render()}else finishLab()}function labWrong(){const e=document.getElementById("labStatus");if(e){e.textContent=lang==="ms"?"Pilihan salah. Cuba lagi.":"Incorrect option. Try again.";e.classList.add("error")}}function finishLab(){lab.tested=true;feedback(lang==="ms"?"Enterprise Lab berjaya!":"Enterprise Lab complete!","good")}
function renderActivity(){const sh=[...pairs.map((p,i)=>({i,text:p.r[lang]}))].sort(()=>Math.random()-.5);return `<div class="activity-board"><div class="activity-col">${pairs.map((p,i)=>`<button class="match-btn ${matched.has(i)?"matched":""}" data-left="${i}" onclick="pickLeft(${i},this)">${p.l[lang]}</button>`).join("")}</div><div class="activity-col">${sh.map(x=>`<button class="match-btn ${matched.has(x.i)?"matched":""}" onclick="pickRight(${x.i},this)">${x.text}</button>`).join("")}</div></div>`}function pickLeft(i,b){selectedLeft=i;document.querySelectorAll("[data-left]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}function pickRight(i,b){if(selectedLeft===i){matched.add(i);render()}else feedback(lang==="ms"?"Belum tepat.":"Not correct.","bad")}
function renderQuiz(){return `<div class="quiz-list">${quiz.map((q,qi)=>`<article class="quiz-card"><h3>${qi+1}. ${q.q[lang]}</h3>${q.o[lang].map((o,oi)=>`<button class="quiz-option ${answers[qi]===oi?"selected":""}" onclick="answer(${qi},${oi},this)">${String.fromCharCode(65+oi)}. ${o}</button>`).join("")}</article>`).join("")}</div>`}function answer(q,o,b){answers[q]=o;render()}
function feedback(t,c){const e=document.getElementById("feedback");if(e){e.textContent=t;e.className="feedback "+c}}function previous(){if(step>0){step--;render()}}function next(){if(slides[step].lab&&!lab.tested){feedback(lang==="ms"?"Lengkapkan Virtual Lab dahulu.":"Complete the Virtual Lab first.","bad");return}if(slides[step].activity&&matched.size<pairs.length){feedback(lang==="ms"?"Lengkapkan semua padanan.":"Complete all matches.","bad");return}if(slides[step].quiz){if(Object.keys(answers).length<quiz.length){feedback(lang==="ms"?"Jawab semua soalan.":"Answer all questions.","bad");return}complete();return}step++;render()}
function complete(){let c=0;quiz.forEach((q,i)=>{if(answers[i]===q.a)c++});const score=Math.round(c/quiz.length*100);state.completedKP=state.completedKP||[];const first=!state.completedKP.includes(13);if(first)state.completedKP.push(13);state.unlocked=13;state.badges=state.badges||[];if(first){state.xp=(state.xp||0)+500+(c*20);state.coins=(state.coins||0)+500;if(!state.badges.includes("grand-master"))state.badges.push("grand-master")}SHStorage.save(state);app.innerHTML=`<section class="center"><div class="card hero"><div class="complete-icon">👑</div><h1>SERVER HERO GRAND MASTER!</h1><div class="score-ring" style="--score:${score*3.6}deg"><b>${score}%</b></div><p>${lang==="ms"?"Tahniah! Semua KP01 hingga KP13 selesai.":"Congratulations! KP01 through KP13 are complete."}</p><button class="primary" onclick="goDashboard()">Dashboard</button><button class="primary" onclick="SHV5.certificate(state)">🎓 Certificate</button></div></section>`}function goDashboard(){window.location.href="index.html"}render();