"use strict";
const REQUIRED_ENGINES=["SERVER_HERO_STORAGE","SERVER_HERO_PLAYER","SERVER_HERO_MISSION_ENGINE","SERVER_HERO_ACHIEVEMENTS","SERVER_HERO_UI"];
REQUIRED_ENGINES.forEach(n=>{if(!window[n])throw new Error(`${n} belum dimuatkan.`)});
const LESSON_ID=10,PASSING_SCORE=80;
const KEYS={simulationCompleted:"lesson10SimulationCompletedV4",matchingCompleted:"lesson10MatchingCompletedV4",quizAnswers:"lesson10QuizAnswersV4",quizScore:"lesson10QuizScoreV4",quizPassed:"lesson10QuizPassedV4",currentQuestion:"lesson10CurrentQuestionV4"};
const Q=[
["Apakah fungsi utama Print Server?",["Mengurus printer, queue dan driver","Memberikan IP","Menyimpan DNS","Mengurus backup"]],
["Apakah fungsi TCP/IP Port?",["Menghubungkan server kepada printer melalui IP","Menyimpan dokumen","Mengurus pengguna","Mengaktifkan DHCP"]],
["Apakah Print Queue?",["Senarai tugasan cetakan","Senarai pengguna","Senarai IP","Senarai GPO"]],
["Apakah fungsi Printer Driver?",["Membolehkan Windows berkomunikasi dengan printer","Menambah RAM","Mengubah domain","Mencipta DNS"]],
["Apakah IP printer dalam misi ini?",["192.168.10.50","192.168.10.10","192.168.10.1","192.168.10.100"]],
["Apakah Share Name printer?",["OFFICE-PRINTER","IT-Share","SERVERHERO-LAN","PRINT01"]],
["Apakah laluan sambungan printer?",["\\\\SERVER\\OFFICE-PRINTER","C:\\OFFICE-PRINTER","D:\\PRINTER","http://printer"]],
["Permission manakah membenarkan pengguna mencetak?",["Print","Manage Printer sahaja","Full Control NTFS","Read DNS"]],
["Mengapa IP printer perlu statik?",["Supaya port printer tidak berubah","Supaya printer lebih laju","Supaya driver dipadam","Supaya domain bertukar"]],
["Apakah ujian akhir?",["Cetak Test Page dari client","Padam printer","Tutup Spooler","Format server"]]
].map(([question,answers])=>({question,answers,correctIndex:0}));
let simulationCompleted=false,matchingCompleted=false,quizPassed=false,currentQuestionIndex=0,selectedAnswers=new Array(Q.length).fill(null);
const $=id=>document.getElementById(id);
const D={playerXP:$("playerXP"),playerRank:$("playerRank"),lessonProgress:$("lessonProgress"),lessonProgressText:$("lessonProgressText"),printerNameInput:$("printerNameInput"),printerIPInput:$("printerIPInput"),portTypeSelect:$("portTypeSelect"),driverStatusSelect:$("driverStatusSelect"),shareNameInput:$("shareNameInput"),printerPathInput:$("printerPathInput"),printPermissionSelect:$("printPermissionSelect"),testPageSelect:$("testPageSelect"),testPrintServerBtn:$("testPrintServerBtn"),resetPrintServerBtn:$("resetPrintServerBtn"),printServerResult:$("printServerResult"),matchingActivity:$("matchingActivity"),checkMatchingBtn:$("checkMatchingBtn"),matchingResult:$("matchingResult"),questionCounter:$("questionCounter"),quizContainer:$("quizContainer"),quizFeedback:$("quizFeedback"),previousQuestionBtn:$("previousQuestionBtn"),nextQuestionBtn:$("nextQuestionBtn"),resultSection:$("resultSection"),resultTitle:$("resultTitle"),resultMessage:$("resultMessage"),finalScore:$("finalScore"),retryQuizBtn:$("retryQuizBtn"),completeMissionBtn:$("completeMissionBtn"),nextMissionBtn:$("nextMissionBtn")};
const norm=v=>String(v||"").trim().toLowerCase().replace(/\s+/g," ");
function load(){simulationCompleted=SERVER_HERO_STORAGE.readRaw(KEYS.simulationCompleted)==="true";matchingCompleted=SERVER_HERO_STORAGE.readRaw(KEYS.matchingCompleted)==="true";quizPassed=SERVER_HERO_STORAGE.readRaw(KEYS.quizPassed)==="true";const a=SERVER_HERO_STORAGE.readArray(KEYS.quizAnswers,[]);if(a.length===Q.length)selectedAnswers=a;currentQuestionIndex=Number(SERVER_HERO_STORAGE.readRaw(KEYS.currentQuestion))||0}
function save(){SERVER_HERO_STORAGE.writeRaw(KEYS.simulationCompleted,String(simulationCompleted));SERVER_HERO_STORAGE.writeRaw(KEYS.matchingCompleted,String(matchingCompleted));SERVER_HERO_STORAGE.writeRaw(KEYS.quizPassed,String(quizPassed));SERVER_HERO_STORAGE.write(KEYS.quizAnswers,selectedAnswers);SERVER_HERO_STORAGE.writeRaw(KEYS.currentQuestion,String(currentQuestionIndex))}
function progress(){let p=10+(simulationCompleted?35:0)+(matchingCompleted?25:0)+Math.round(selectedAnswers.filter(x=>x!==null).length/Q.length*15)+(quizPassed?15:0);p=Math.min(p,100);SERVER_HERO_UI.animateProgress(D.lessonProgress,p,500);D.lessonProgressText.textContent=p+"%"}
function mark(el,ok){el.classList.remove("valid","invalid");el.classList.add(ok?"valid":"invalid")}
function testConfig(){const c={n:norm(D.printerNameInput.value)==="office printer",ip:D.printerIPInput.value.trim()==="192.168.10.50",p:D.portTypeSelect.value==="standard-tcpip",d:D.driverStatusSelect.value==="installed",s:norm(D.shareNameInput.value)==="office-printer",path:norm(D.printerPathInput.value)==="\\\\server\\office-printer",perm:D.printPermissionSelect.value==="print",t:D.testPageSelect.value==="success"};[D.printerNameInput,D.printerIPInput,D.portTypeSelect,D.driverStatusSelect,D.shareNameInput,D.printerPathInput,D.printPermissionSelect,D.testPageSelect].forEach((e,i)=>mark(e,Object.values(c)[i]));simulationCompleted=Object.values(c).every(Boolean);D.printServerResult.textContent=simulationCompleted?"✅ Print Server berjaya dikonfigurasi.":"❌ Semak semua tetapan Print Server.";D.printServerResult.className="feedback-box "+(simulationCompleted?"correct":"wrong");save();progress();completion()}
function reset(){[D.printerNameInput,D.printerIPInput,D.portTypeSelect,D.driverStatusSelect,D.shareNameInput,D.printerPathInput,D.printPermissionSelect,D.testPageSelect].forEach(e=>{e.value="";e.classList.remove("valid","invalid")});simulationCompleted=false;D.printServerResult.textContent="Lengkapkan semua tetapan Print Server.";D.printServerResult.className="feedback-box";save();progress();completion()}
function matching(){const ss=[...D.matchingActivity.querySelectorAll("select[data-answer]")];if(ss.some(s=>!s.value))return SERVER_HERO_UI.toast("Lengkapkan semua padanan dahulu.","error");let n=0;ss.forEach(s=>{const ok=s.value===s.dataset.answer;s.closest("article").className=ok?"correct":"wrong";if(ok)n++});matchingCompleted=n===ss.length;D.matchingResult.textContent=matchingCompleted?"✅ Semua padanan betul.":`❌ ${n} daripada ${ss.length} padanan betul.`;D.matchingResult.className="feedback-box "+(matchingCompleted?"correct":"wrong");save();progress();completion()}
function render(){const q=Q[currentQuestionIndex];D.quizContainer.innerHTML=`<div class="quiz-question"><h3>${SERVER_HERO_UI.escapeHTML(q.question)}</h3></div><div class="answer-list">${q.answers.map((a,i)=>`<button class="answer-option ${selectedAnswers[currentQuestionIndex]===i?"selected":""}" data-i="${i}">${SERVER_HERO_UI.escapeHTML(a)}</button>`).join("")}</div>`;D.quizContainer.querySelectorAll("button").forEach(b=>b.onclick=()=>{selectedAnswers[currentQuestionIndex]=Number(b.dataset.i);render()});D.questionCounter.textContent=`${currentQuestionIndex+1} / ${Q.length}`;D.previousQuestionBtn.disabled=currentQuestionIndex===0;D.nextQuestionBtn.textContent=currentQuestionIndex===Q.length-1?"Hantar Kuiz":"Seterusnya";D.quizFeedback.textContent=selectedAnswers[currentQuestionIndex]===null?"Pilih satu jawapan.":"Jawapan telah dipilih.";save();progress()}
function submit(){const correct=Q.reduce((t,q,i)=>t+(selectedAnswers[i]===q.correctIndex?1:0),0),pct=Math.round(correct/Q.length*100);quizPassed=pct>=PASSING_SCORE;SERVER_HERO_STORAGE.writeRaw(KEYS.quizScore,String(pct));SERVER_HERO_STORAGE.writeRaw(KEYS.quizPassed,String(quizPassed));SERVER_HERO_STORAGE.setMissionQuizPassed(LESSON_ID,quizPassed);D.resultSection.classList.remove("hidden");D.finalScore.textContent=pct+"%";D.resultTitle.textContent=quizPassed?"Tahniah, Anda Lulus!":"Belum Mencapai Markah Lulus";D.resultMessage.textContent=`Anda menjawab ${correct} daripada ${Q.length} soalan dengan betul.`;save();progress();completion()}
function completion(){const done=SERVER_HERO_MISSION_ENGINE.isCompleted(LESSON_ID),can=simulationCompleted&&matchingCompleted&&quizPassed;D.completeMissionBtn.disabled=!can||done;D.completeMissionBtn.textContent=done?"✓ Misi Telah Selesai":can?"Lengkapkan Misi 10":"🔒 Lengkapkan Misi 10";D.nextMissionBtn.disabled=!done;if(done)D.nextMissionBtn.onclick=()=>location.href="lesson11.html"}
function complete(){if(!(simulationCompleted&&matchingCompleted&&quizPassed))return;const r=SERVER_HERO_MISSION_ENGINE.complete(LESSON_ID);if(r.success){SERVER_HERO_ACHIEVEMENTS.check();completion();SERVER_HERO_UI.modal({title:"Misi 10 Selesai",message:"Mission 11 kini dibuka.",icon:"🖨️",confirmText:"Dashboard",onConfirm(){location.href="index.html"}})}}
D.testPrintServerBtn.onclick=testConfig;D.resetPrintServerBtn.onclick=reset;D.checkMatchingBtn.onclick=matching;D.previousQuestionBtn.onclick=()=>{if(currentQuestionIndex>0){currentQuestionIndex--;render()}};D.nextQuestionBtn.onclick=()=>{if(selectedAnswers[currentQuestionIndex]===null)return SERVER_HERO_UI.toast("Pilih jawapan dahulu.","error");if(currentQuestionIndex<Q.length-1){currentQuestionIndex++;render()}else submit()};D.retryQuizBtn.onclick=()=>{selectedAnswers=new Array(Q.length).fill(null);currentQuestionIndex=0;quizPassed=false;D.resultSection.classList.add("hidden");save();render();completion()};D.completeMissionBtn.onclick=complete;
load();render();const p=SERVER_HERO_PLAYER.get();D.playerXP.textContent=p.xp;D.playerRank.textContent=p.rank;progress();completion();
