window.missions = [
  {
    "id": 1,
    "title": "MISSION 01",
    "subtitle": "Install Windows Server 2019",
    "description": "Install Windows Server 2019 and prepare the operating system for server deployment.",
    "xp": 250,
    "coins": 50,
    "gems": 2,
    "difficulty": "Easy",
    "duration": "20 Minutes",
    "icon": "💻",
    "page": "lesson1.html"
  },
  {
    "id": 2,
    "title": "MISSION 02",
    "subtitle": "Configure Static IP Address",
    "description": "Configure a static IPv4 address, subnet mask, gateway and preferred DNS server.",
    "xp": 300,
    "coins": 60,
    "gems": 2,
    "difficulty": "Easy",
    "duration": "20 Minutes",
    "icon": "🌐",
    "page": "lesson2.html"
  },
  {
    "id": 3,
    "title": "MISSION 03",
    "subtitle": "Install Active Directory Domain Services",
    "description": "Install AD DS and promote the server as a Domain Controller.",
    "xp": 450,
    "coins": 75,
    "gems": 3,
    "difficulty": "Medium",
    "duration": "30 Minutes",
    "icon": "🏢",
    "page": "lesson3.html"
  },
  {
    "id": 4,
    "title": "MISSION 04",
    "subtitle": "Configure DNS Server",
    "description": "Configure DNS zones and verify name resolution using nslookup.",
    "xp": 450,
    "coins": 75,
    "gems": 3,
    "difficulty": "Medium",
    "duration": "30 Minutes",
    "icon": "🛰️",
    "page": "lesson4.html"
  },
  {
    "id": 5,
    "title": "MISSION 05",
    "subtitle": "Configure DHCP Server",
    "description": "Install DHCP Server, create a scope and activate the service.",
    "xp": 500,
    "coins": 90,
    "gems": 4,
    "difficulty": "Medium",
    "duration": "35 Minutes",
    "icon": "📡",
    "page": "lesson5.html"
  },
  {
    "id": 6,
    "title": "MISSION 06",
    "subtitle": "Create Organizational Unit & User",
    "description": "Create OUs, users and groups in Active Directory.",
    "xp": 600,
    "coins": 100,
    "gems": 5,
    "difficulty": "Hard",
    "duration": "40 Minutes",
    "icon": "👥",
    "page": "lesson6.html"
  },
  {
    "id": 7,
    "title": "MISSION 07",
    "subtitle": "Join Windows 10 Client to Domain",
    "description": "Join a Windows 10 client computer to the Active Directory domain.",
    "xp": 700,
    "coins": 120,
    "gems": 5,
    "difficulty": "Hard",
    "duration": "40 Minutes",
    "icon": "🖥️",
    "page": "lesson7.html"
  },
  {
    "id": 8,
    "title": "MISSION 08",
    "subtitle": "Final Server Validation",
    "description": "Validate AD DS, DNS, DHCP and client connectivity.",
    "xp": 1000,
    "coins": 200,
    "gems": 10,
    "difficulty": "Expert",
    "duration": "60 Minutes",
    "icon": "🏆",
    "page": "lesson8.html"
  }
];
